#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_PlayerNpc_Toolbox

#include "Basic.hpp"

#include "ABP_PlayerNpc_Toolbox_classes.hpp"
#include "ABP_PlayerNpc_Toolbox_parameters.hpp"


namespace SDK
{

// Function ABP_PlayerNpc_Toolbox.ABP_PlayerNpc_Toolbox_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UABP_PlayerNpc_Toolbox_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_PlayerNpc_Toolbox_C", "AnimGraph");

	Params::ABP_PlayerNpc_Toolbox_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}


// Function ABP_PlayerNpc_Toolbox.ABP_PlayerNpc_Toolbox_C.AnimNotify_stepLeft
// (BlueprintCallable, BlueprintEvent)

void UABP_PlayerNpc_Toolbox_C::AnimNotify_stepLeft()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_PlayerNpc_Toolbox_C", "AnimNotify_stepLeft");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_PlayerNpc_Toolbox.ABP_PlayerNpc_Toolbox_C.AnimNotify_stepRight
// (BlueprintCallable, BlueprintEvent)

void UABP_PlayerNpc_Toolbox_C::AnimNotify_stepRight()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_PlayerNpc_Toolbox_C", "AnimNotify_stepRight");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_PlayerNpc_Toolbox.ABP_PlayerNpc_Toolbox_C.BlueprintThreadSafeUpdateAnimation
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   DeltaTime                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UABP_PlayerNpc_Toolbox_C::BlueprintThreadSafeUpdateAnimation(float DeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_PlayerNpc_Toolbox_C", "BlueprintThreadSafeUpdateAnimation");

	Params::ABP_PlayerNpc_Toolbox_C_BlueprintThreadSafeUpdateAnimation Parms{};

	Parms.DeltaTime = DeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_PlayerNpc_Toolbox.ABP_PlayerNpc_Toolbox_C.BlueprintUpdateAnimation
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaTimeX                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UABP_PlayerNpc_Toolbox_C::BlueprintUpdateAnimation(float DeltaTimeX)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_PlayerNpc_Toolbox_C", "BlueprintUpdateAnimation");

	Params::ABP_PlayerNpc_Toolbox_C_BlueprintUpdateAnimation Parms{};

	Parms.DeltaTimeX = DeltaTimeX;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_PlayerNpc_Toolbox.ABP_PlayerNpc_Toolbox_C.ExecuteUbergraph_ABP_PlayerNpc_Toolbox
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UABP_PlayerNpc_Toolbox_C::ExecuteUbergraph_ABP_PlayerNpc_Toolbox(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_PlayerNpc_Toolbox_C", "ExecuteUbergraph_ABP_PlayerNpc_Toolbox");

	Params::ABP_PlayerNpc_Toolbox_C_ExecuteUbergraph_ABP_PlayerNpc_Toolbox Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

