#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_Goblin

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "AnimGraphRuntime_structs.hpp"
#include "ABP_Goblin_structs.hpp"
#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass ABP_Goblin.ABP_Goblin_C
// 0x0320 (0x0710 - 0x03F0)
class UABP_Goblin_C final : public UAnimInstance
{
public:
	uint8                                         Pad_3E8[0x8];                                      // 0x03E8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct ABP_Goblin::FAnimBlueprintGeneratedMutableData __AnimBlueprintMutables;                   // 0x03F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_PropertyAccess;             // 0x03F8(0x0008)()
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_Base;                       // 0x0400(0x0008)()
	struct FAnimNode_BlendSpacePlayer             AnimGraphNode_BlendSpacePlayer;                    // 0x0408(0x0070)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose;                      // 0x0478(0x0080)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot_1;                              // 0x04F8(0x0048)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot;                                // 0x0540(0x0048)()
	struct FAnimNode_LayeredBoneBlend             AnimGraphNode_LayeredBoneBlend;                    // 0x0588(0x00E8)()
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x0670(0x0020)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_1;                     // 0x0690(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose;                       // 0x06B8(0x0028)()
	struct FVector                                K2Node_PropertyAccess;                             // 0x06E0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Speed;                                             // 0x06F8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  Owner;                                             // 0x0700(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void AnimGraph(struct FPoseLink* AnimGraph_0);
	void BlueprintThreadSafeUpdateAnimation(float DeltaTime);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ABP_Goblin_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ABP_Goblin_C")
	}
	static class UABP_Goblin_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UABP_Goblin_C>();
	}
};
DUMPER7_ASSERTS_UABP_Goblin_C;

}

