#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ArrowProjectile

#include "Basic.hpp"

#include "BP_ArrowProjectile_classes.hpp"
#include "BP_ArrowProjectile_parameters.hpp"


namespace SDK
{

// Function BP_ArrowProjectile.BP_ArrowProjectile_C.BndEvt__BP_ArrowProjectile_Box_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// class UPrimitiveComponent*              HitComponent_0                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              OtherComp                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   NormalImpulse                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FHitResult&                Hit_0                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void ABP_ArrowProjectile_C::BndEvt__BP_ArrowProjectile_Box_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature(class UPrimitiveComponent* HitComponent_0, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, const struct FVector& NormalImpulse, const struct FHitResult& Hit_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ArrowProjectile_C", "BndEvt__BP_ArrowProjectile_Box_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature");

	Params::BP_ArrowProjectile_C_BndEvt__BP_ArrowProjectile_Box_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature Parms{};

	Parms.HitComponent_0 = HitComponent_0;
	Parms.OtherActor = OtherActor;
	Parms.OtherComp = OtherComp;
	Parms.NormalImpulse = std::move(NormalImpulse);
	Parms.Hit_0 = std::move(Hit_0);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ArrowProjectile.BP_ArrowProjectile_C.BndEvt__BP_ArrowProjectile_Box_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// class UPrimitiveComponent*              OverlappedComponent                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              OtherComp                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// int32                                   OtherBodyIndex                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bFromSweep                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FHitResult&                SweepResult                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void ABP_ArrowProjectile_C::BndEvt__BP_ArrowProjectile_Box_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const struct FHitResult& SweepResult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ArrowProjectile_C", "BndEvt__BP_ArrowProjectile_Box_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature");

	Params::BP_ArrowProjectile_C_BndEvt__BP_ArrowProjectile_Box_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature Parms{};

	Parms.OverlappedComponent = OverlappedComponent;
	Parms.OtherActor = OtherActor;
	Parms.OtherComp = OtherComp;
	Parms.OtherBodyIndex = OtherBodyIndex;
	Parms.bFromSweep = bFromSweep;
	Parms.SweepResult = std::move(SweepResult);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ArrowProjectile.BP_ArrowProjectile_C.ExecuteUbergraph_BP_ArrowProjectile
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_ArrowProjectile_C::ExecuteUbergraph_BP_ArrowProjectile(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ArrowProjectile_C", "ExecuteUbergraph_BP_ArrowProjectile");

	Params::BP_ArrowProjectile_C_ExecuteUbergraph_BP_ArrowProjectile Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ArrowProjectile.BP_ArrowProjectile_C.F_DestroyAttachedActor
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           DestroyedActor                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_ArrowProjectile_C::F_DestroyAttachedActor(class AActor* DestroyedActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ArrowProjectile_C", "F_DestroyAttachedActor");

	Params::BP_ArrowProjectile_C_F_DestroyAttachedActor Parms{};

	Parms.DestroyedActor = DestroyedActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ArrowProjectile.BP_ArrowProjectile_C.F_ElementExplosion
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             Acid                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             Fire                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             Electric                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_ArrowProjectile_C::F_ElementExplosion(class FName Acid, class FName Fire, class FName Electric)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ArrowProjectile_C", "F_ElementExplosion");

	Params::BP_ArrowProjectile_C_F_ElementExplosion Parms{};

	Parms.Acid = Acid;
	Parms.Fire = Fire;
	Parms.Electric = Electric;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ArrowProjectile.BP_ArrowProjectile_C.F_EnableEnemyCollisions
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_ArrowProjectile_C::F_EnableEnemyCollisions()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ArrowProjectile_C", "F_EnableEnemyCollisions");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ArrowProjectile.BP_ArrowProjectile_C.F_IsCritical
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FHitResult&                Hit_0                                                  (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
// bool*                                   Critical                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_ArrowProjectile_C::F_IsCritical(const struct FHitResult& Hit_0, bool* Critical)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ArrowProjectile_C", "F_IsCritical");

	Params::BP_ArrowProjectile_C_F_IsCritical Parms{};

	Parms.Hit_0 = std::move(Hit_0);

	UObject::ProcessEvent(Func, &Parms);

	if (Critical != nullptr)
		*Critical = Parms.Critical;
}


// Function BP_ArrowProjectile.BP_ArrowProjectile_C.F_TriggerArrowExplodesOnHit
// (BlueprintCallable, BlueprintEvent)

void ABP_ArrowProjectile_C::F_TriggerArrowExplodesOnHit()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ArrowProjectile_C", "F_TriggerArrowExplodesOnHit");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ArrowProjectile.BP_ArrowProjectile_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_ArrowProjectile_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ArrowProjectile_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ArrowProjectile.BP_ArrowProjectile_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_ArrowProjectile_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ArrowProjectile_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

