#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CrypticLaser

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_CrypticLaser.BP_CrypticLaser_C
// 0x0030 (0x02E0 - 0x02B0)
class ABP_CrypticLaser_C final : public AActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02B0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UStaticMeshComponent*                   StaticMesh;                                        // 0x02B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x02C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	float                                         T_Attack_Alpha_DE1A5C6F41E12685BF73909C2EC49190;   // 0x02C8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            T_Attack__Direction_DE1A5C6F41E12685BF73909C2EC49190; // 0x02CC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2CD[0x3];                                      // 0x02CD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     T_Attack;                                          // 0x02D0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	float                                         MaxDistance;                                       // 0x02D8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_CrypticLaser(int32 EntryPoint);
	void F_InitMaxDistance();
	void ReceiveBeginPlay();
	void T_Attack__FinishedFunc();
	void T_Attack__Hit__EventFunc();
	void T_Attack__UpdateFunc();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_CrypticLaser_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_CrypticLaser_C")
	}
	static class ABP_CrypticLaser_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_CrypticLaser_C>();
	}
};
DUMPER7_ASSERTS_ABP_CrypticLaser_C;

}

