#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DamageIndicator

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_DamageIndicator.BP_DamageIndicator_C
// 0x0010 (0x02C0 - 0x02B0)
class ABP_DamageIndicator_C final : public AActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02B0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x02B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_DamageIndicator(int32 EntryPoint);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_DamageIndicator_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_DamageIndicator_C")
	}
	static class ABP_DamageIndicator_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_DamageIndicator_C>();
	}
};
DUMPER7_ASSERTS_ABP_DamageIndicator_C;

}

