#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DeathAnimation_Horseman

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_DeathAnimation_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_DeathAnimation_Horseman.BP_DeathAnimation_Horseman_C
// 0x0038 (0x02F0 - 0x02B8)
class ABP_DeathAnimation_Horseman_C final : public ABP_DeathAnimation_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02B8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UAudioComponent*                        S_Horseman_Death;                                  // 0x02C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UNiagaraComponent*                      Niagara;                                           // 0x02C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UNiagaraComponent*                      Niagara1;                                          // 0x02D0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 SkeletalMesh;                                      // 0x02D8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	float                                         Timeline_Alpha_CC193FF44761340FB5C6AFA0FD232126;   // 0x02E0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            Timeline__Direction_CC193FF44761340FB5C6AFA0FD232126; // 0x02E4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2E5[0x3];                                      // 0x02E5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     Timeline;                                          // 0x02E8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_DeathAnimation_Horseman(int32 EntryPoint);
	void ReceiveBeginPlay();
	void Timeline__FinishedFunc();
	void Timeline__UpdateFunc();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_DeathAnimation_Horseman_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_DeathAnimation_Horseman_C")
	}
	static class ABP_DeathAnimation_Horseman_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_DeathAnimation_Horseman_C>();
	}
};
DUMPER7_ASSERTS_ABP_DeathAnimation_Horseman_C;

}

