#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Enemy_PumpkinMan

#include "Basic.hpp"

#include "BP_Enemy_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Enemy_PumpkinMan.BP_Enemy_PumpkinMan_C
// 0x0010 (0x08F0 - 0x08E0)
class ABP_Enemy_PumpkinMan_C final : public ABP_Enemy_C
{
public:
	uint8                                         Pad_8D1[0x7];                                      // 0x08D1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_Enemy_PumpkinMan_C;              // 0x08D8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	double                                        pulserSpeed;                                       // 0x08E0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_Enemy_PumpkinMan(int32 EntryPoint);
	void F_Chase();
	void F_StartAI();
	void ReceiveDestroyed();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Enemy_PumpkinMan_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Enemy_PumpkinMan_C")
	}
	static class ABP_Enemy_PumpkinMan_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Enemy_PumpkinMan_C>();
	}
};
DUMPER7_ASSERTS_ABP_Enemy_PumpkinMan_C;

}

