#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Enemy_Cryptic_Grenadier

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function BP_Enemy_Cryptic_Grenadier.BP_Enemy_Cryptic_Grenadier_C.ExecuteUbergraph_BP_Enemy_Cryptic_Grenadier
// 0x00B8 (0x00B8 - 0x0000)
struct BP_Enemy_Cryptic_Grenadier_C_ExecuteUbergraph_BP_Enemy_Cryptic_Grenadier final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPlayMontageCallbackProxy*              CallFunc_CreateProxyObjectForPlayMontage_ReturnValue; // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate;              // 0x0010(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_21[0x3];                                       // 0x0021(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   K2Node_CustomEvent_NotifyName_4;                   // 0x0024(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   K2Node_CustomEvent_NotifyName_3;                   // 0x002C(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate_1;            // 0x0034(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate_2;            // 0x0044(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FName                                   K2Node_CustomEvent_NotifyName_2;                   // 0x0054(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   K2Node_CustomEvent_NotifyName_1;                   // 0x005C(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate_3;            // 0x0064(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate_4;            // 0x0074(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FName                                   K2Node_CustomEvent_NotifyName;                     // 0x0084(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   Temp_name_Variable;                                // 0x008C(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_94[0x4];                                       // 0x0094(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0098(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UNiagaraComponent*                      CallFunc_SpawnSystemAtLocation_ReturnValue;        // 0x00B0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_Enemy_Cryptic_Grenadier_C_ExecuteUbergraph_BP_Enemy_Cryptic_Grenadier;

// Function BP_Enemy_Cryptic_Grenadier.BP_Enemy_Cryptic_Grenadier_C.OnBlendOut_DAECD05049FEA4327679D18726477174
// 0x0008 (0x0008 - 0x0000)
struct BP_Enemy_Cryptic_Grenadier_C_OnBlendOut_DAECD05049FEA4327679D18726477174 final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_Enemy_Cryptic_Grenadier_C_OnBlendOut_DAECD05049FEA4327679D18726477174;

// Function BP_Enemy_Cryptic_Grenadier.BP_Enemy_Cryptic_Grenadier_C.OnCompleted_DAECD05049FEA4327679D18726477174
// 0x0008 (0x0008 - 0x0000)
struct BP_Enemy_Cryptic_Grenadier_C_OnCompleted_DAECD05049FEA4327679D18726477174 final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_Enemy_Cryptic_Grenadier_C_OnCompleted_DAECD05049FEA4327679D18726477174;

// Function BP_Enemy_Cryptic_Grenadier.BP_Enemy_Cryptic_Grenadier_C.OnInterrupted_DAECD05049FEA4327679D18726477174
// 0x0008 (0x0008 - 0x0000)
struct BP_Enemy_Cryptic_Grenadier_C_OnInterrupted_DAECD05049FEA4327679D18726477174 final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_Enemy_Cryptic_Grenadier_C_OnInterrupted_DAECD05049FEA4327679D18726477174;

// Function BP_Enemy_Cryptic_Grenadier.BP_Enemy_Cryptic_Grenadier_C.OnNotifyBegin_DAECD05049FEA4327679D18726477174
// 0x0008 (0x0008 - 0x0000)
struct BP_Enemy_Cryptic_Grenadier_C_OnNotifyBegin_DAECD05049FEA4327679D18726477174 final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_Enemy_Cryptic_Grenadier_C_OnNotifyBegin_DAECD05049FEA4327679D18726477174;

// Function BP_Enemy_Cryptic_Grenadier.BP_Enemy_Cryptic_Grenadier_C.OnNotifyEnd_DAECD05049FEA4327679D18726477174
// 0x0008 (0x0008 - 0x0000)
struct BP_Enemy_Cryptic_Grenadier_C_OnNotifyEnd_DAECD05049FEA4327679D18726477174 final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_Enemy_Cryptic_Grenadier_C_OnNotifyEnd_DAECD05049FEA4327679D18726477174;

}

