#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_EnemyProjectile_CactusTurret_Fire

#include "Basic.hpp"

#include "BP_EnemyProjectile_CactusTurret_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_EnemyProjectile_CactusTurret_Fire.BP_EnemyProjectile_CactusTurret_Fire_C
// 0x0000 (0x0368 - 0x0368)
class ABP_EnemyProjectile_CactusTurret_Fire_C final : public ABP_EnemyProjectile_CactusTurret_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_EnemyProjectile_CactusTurret_Fire_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_EnemyProjectile_CactusTurret_Fire_C")
	}
	static class ABP_EnemyProjectile_CactusTurret_Fire_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_EnemyProjectile_CactusTurret_Fire_C>();
	}
};
DUMPER7_ASSERTS_ABP_EnemyProjectile_CactusTurret_Fire_C;

}

