#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Event

#include "Basic.hpp"

#include "BP_Event_classes.hpp"
#include "BP_Event_parameters.hpp"


namespace SDK
{

// Function BP_Event.BP_Event_C.F_ReactivateActors
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_Event_C::F_ReactivateActors()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Event_C", "F_ReactivateActors");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Event.BP_Event_C.F_DeactivateActors
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_Event_C::F_DeactivateActors()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Event_C", "F_DeactivateActors");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Event.BP_Event_C.OnRep_eventRunning
// (BlueprintCallable, BlueprintEvent)

void ABP_Event_C::OnRep_eventRunning()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Event_C", "OnRep_eventRunning");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Event.BP_Event_C.OnRep_stormIntensity
// (BlueprintCallable, BlueprintEvent)

void ABP_Event_C::OnRep_stormIntensity()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Event_C", "OnRep_stormIntensity");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Event.BP_Event_C.F_SpawnActorAheadOfPlayer
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// TSubclassOf<class AActor>               Actor                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
// float                                   Distance                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool*                                   Success                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Event_C::F_SpawnActorAheadOfPlayer(TSubclassOf<class AActor> Actor, float Distance, bool* Success)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Event_C", "F_SpawnActorAheadOfPlayer");

	Params::BP_Event_C_F_SpawnActorAheadOfPlayer Parms{};

	Parms.Actor = Actor;
	Parms.Distance = Distance;

	UObject::ProcessEvent(Func, &Parms);

	if (Success != nullptr)
		*Success = Parms.Success;
}


// Function BP_Event.BP_Event_C.F_UpdateStormIntensity
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_Event_C::F_UpdateStormIntensity()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Event_C", "F_UpdateStormIntensity");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Event.BP_Event_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_Event_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Event_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Event.BP_Event_C.Appear__FinishedFunc
// (BlueprintEvent)

void ABP_Event_C::Appear__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Event_C", "Appear__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Event.BP_Event_C.Appear__UpdateFunc
// (BlueprintEvent)

void ABP_Event_C::Appear__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Event_C", "Appear__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Event.BP_Event_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_Event_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Event_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Event.BP_Event_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Event_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Event_C", "ReceiveTick");

	Params::BP_Event_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Event.BP_Event_C.F_AppearStorm
// (BlueprintCallable, BlueprintEvent)

void ABP_Event_C::F_AppearStorm()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Event_C", "F_AppearStorm");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Event.BP_Event_C.F_DisappearStorm
// (BlueprintCallable, BlueprintEvent)

void ABP_Event_C::F_DisappearStorm()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Event_C", "F_DisappearStorm");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Event.BP_Event_C.F_StopEvent
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    OverseerTalks                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   EndTime                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Event_C::F_StopEvent(bool OverseerTalks, float EndTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Event_C", "F_StopEvent");

	Params::BP_Event_C_F_StopEvent Parms{};

	Parms.OverseerTalks = OverseerTalks;
	Parms.EndTime = EndTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Event.BP_Event_C.F_Child_StopEvent
// (BlueprintCallable, BlueprintEvent)

void ABP_Event_C::F_Child_StopEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Event_C", "F_Child_StopEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Event.BP_Event_C.F_Child_StartEvent
// (BlueprintCallable, BlueprintEvent)

void ABP_Event_C::F_Child_StartEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Event_C", "F_Child_StartEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Event.BP_Event_C.F_StopMusic
// (BlueprintCallable, BlueprintEvent)

void ABP_Event_C::F_StopMusic()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Event_C", "F_StopMusic");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Event.BP_Event_C.F_RetriggrerEvent
// (BlueprintCallable, BlueprintEvent)

void ABP_Event_C::F_RetriggrerEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Event_C", "F_RetriggrerEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Event.BP_Event_C.ReceiveDestroyed
// (Event, Public, BlueprintEvent)

void ABP_Event_C::ReceiveDestroyed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Event_C", "ReceiveDestroyed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Event.BP_Event_C.ExecuteUbergraph_BP_Event
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Event_C::ExecuteUbergraph_BP_Event(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Event_C", "ExecuteUbergraph_BP_Event");

	Params::BP_Event_C_ExecuteUbergraph_BP_Event Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

