#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Grenade_Impulse

#include "Basic.hpp"

#include "BP_Grenade_Impulse_classes.hpp"
#include "BP_Grenade_Impulse_parameters.hpp"


namespace SDK
{

// Function BP_Grenade_Impulse.BP_Grenade_Impulse_C.ExecuteUbergraph_BP_Grenade_Impulse
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Grenade_Impulse_C::ExecuteUbergraph_BP_Grenade_Impulse(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Grenade_Impulse_C", "ExecuteUbergraph_BP_Grenade_Impulse");

	Params::BP_Grenade_Impulse_C_ExecuteUbergraph_BP_Grenade_Impulse Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Grenade_Impulse.BP_Grenade_Impulse_C.F_Child_Explode
// (BlueprintCallable, BlueprintEvent)

void ABP_Grenade_Impulse_C::F_Child_Explode()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Grenade_Impulse_C", "F_Child_Explode");

	UObject::ProcessEvent(Func, nullptr);
}

}

