#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ItemPreview_Kwartsman

#include "Basic.hpp"

#include "BP_ItemPreview_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ItemPreview_Kwartsman.BP_ItemPreview_Kwartsman_C
// 0x0000 (0x02D8 - 0x02D8)
class ABP_ItemPreview_Kwartsman_C final : public ABP_ItemPreview_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ItemPreview_Kwartsman_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ItemPreview_Kwartsman_C")
	}
	static class ABP_ItemPreview_Kwartsman_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_ItemPreview_Kwartsman_C>();
	}
};
DUMPER7_ASSERTS_ABP_ItemPreview_Kwartsman_C;

}

