#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Item_Disc_TrainOfShame

#include "Basic.hpp"

#include "BP_Item_Disc_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Item_Disc_TrainOfShame.BP_Item_Disc_TrainOfShame_C
// 0x0000 (0x04C0 - 0x04C0)
class ABP_Item_Disc_TrainOfShame_C final : public ABP_Item_Disc_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Item_Disc_TrainOfShame_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Item_Disc_TrainOfShame_C")
	}
	static class ABP_Item_Disc_TrainOfShame_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Item_Disc_TrainOfShame_C>();
	}
};
DUMPER7_ASSERTS_ABP_Item_Disc_TrainOfShame_C;

}

