#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Item_Pistol

#include "Basic.hpp"

#include "BP_Item_Pistol_classes.hpp"
#include "BP_Item_Pistol_parameters.hpp"


namespace SDK
{

// Function BP_Item_Pistol.BP_Item_Pistol_C.ExecuteUbergraph_BP_Item_Pistol
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::ExecuteUbergraph_BP_Item_Pistol(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "ExecuteUbergraph_BP_Item_Pistol");

	Params::BP_Item_Pistol_C_ExecuteUbergraph_BP_Item_Pistol Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.F_CanTriggerJokerFanningAce
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool ABP_Item_Pistol_C::F_CanTriggerJokerFanningAce()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "F_CanTriggerJokerFanningAce");

	Params::BP_Item_Pistol_C_F_CanTriggerJokerFanningAce Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.F_Child_Inspect
// (BlueprintCallable, BlueprintEvent)

void ABP_Item_Pistol_C::F_Child_Inspect()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "F_Child_Inspect");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.F_Child_Reload
// (BlueprintCallable, BlueprintEvent)

void ABP_Item_Pistol_C::F_Child_Reload()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "F_Child_Reload");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.F_Child_Shoot
// (BlueprintCallable, BlueprintEvent)

void ABP_Item_Pistol_C::F_Child_Shoot()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "F_Child_Shoot");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.F_Child_StartAim
// (BlueprintCallable, BlueprintEvent)

void ABP_Item_Pistol_C::F_Child_StartAim()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "F_Child_StartAim");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.F_Child_StopAim
// (BlueprintCallable, BlueprintEvent)

void ABP_Item_Pistol_C::F_Child_StopAim()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "F_Child_StopAim");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.F_ChildTryShootDuringReload
// (BlueprintCallable, BlueprintEvent)

void ABP_Item_Pistol_C::F_ChildTryShootDuringReload()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "F_ChildTryShootDuringReload");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.F_Muzzle
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_Item_Pistol_C::F_Muzzle()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "F_Muzzle");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.F_PlayMontageAnimationReplicated
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Wildcard                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UAnimMontage*                     MontageForHands                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UAnimMontage*                     MontageForItem                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class USoundBase*                       Sound                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class USoundAttenuation*                AttenuationSettings                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::F_PlayMontageAnimationReplicated(int32 Wildcard, class UAnimMontage* MontageForHands, class UAnimMontage* MontageForItem, class USoundBase* Sound, class USoundAttenuation* AttenuationSettings)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "F_PlayMontageAnimationReplicated");

	Params::BP_Item_Pistol_C_F_PlayMontageAnimationReplicated Parms{};

	Parms.Wildcard = Wildcard;
	Parms.MontageForHands = MontageForHands;
	Parms.MontageForItem = MontageForItem;
	Parms.Sound = Sound;
	Parms.AttenuationSettings = AttenuationSettings;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.F_UpdatePistolColor
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_Item_Pistol_C::F_UpdatePistolColor()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "F_UpdatePistolColor");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.OnBlendOut_1966F0C0404D446918EDC1BA9E0AE10D
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::OnBlendOut_1966F0C0404D446918EDC1BA9E0AE10D(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "OnBlendOut_1966F0C0404D446918EDC1BA9E0AE10D");

	Params::BP_Item_Pistol_C_OnBlendOut_1966F0C0404D446918EDC1BA9E0AE10D Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.OnBlendOut_28B7E75842493FF7C0642EAD62EAAE5B
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::OnBlendOut_28B7E75842493FF7C0642EAD62EAAE5B(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "OnBlendOut_28B7E75842493FF7C0642EAD62EAAE5B");

	Params::BP_Item_Pistol_C_OnBlendOut_28B7E75842493FF7C0642EAD62EAAE5B Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.OnBlendOut_2F55E14E4CDE96EBB3363BA5C7B412AB
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::OnBlendOut_2F55E14E4CDE96EBB3363BA5C7B412AB(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "OnBlendOut_2F55E14E4CDE96EBB3363BA5C7B412AB");

	Params::BP_Item_Pistol_C_OnBlendOut_2F55E14E4CDE96EBB3363BA5C7B412AB Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.OnBlendOut_45E13C734FB393DCFAE5ABB5CC9473FB
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::OnBlendOut_45E13C734FB393DCFAE5ABB5CC9473FB(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "OnBlendOut_45E13C734FB393DCFAE5ABB5CC9473FB");

	Params::BP_Item_Pistol_C_OnBlendOut_45E13C734FB393DCFAE5ABB5CC9473FB Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.OnBlendOut_630B46B841FC7C8FC0E1CBA4A9E2190F
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::OnBlendOut_630B46B841FC7C8FC0E1CBA4A9E2190F(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "OnBlendOut_630B46B841FC7C8FC0E1CBA4A9E2190F");

	Params::BP_Item_Pistol_C_OnBlendOut_630B46B841FC7C8FC0E1CBA4A9E2190F Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.OnBlendOut_7BD1D9B44937E94B4C7143A26722060F
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::OnBlendOut_7BD1D9B44937E94B4C7143A26722060F(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "OnBlendOut_7BD1D9B44937E94B4C7143A26722060F");

	Params::BP_Item_Pistol_C_OnBlendOut_7BD1D9B44937E94B4C7143A26722060F Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.OnBlendOut_7FFB8CC54B246D4BCE5C6CAEFFF1B0E0
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::OnBlendOut_7FFB8CC54B246D4BCE5C6CAEFFF1B0E0(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "OnBlendOut_7FFB8CC54B246D4BCE5C6CAEFFF1B0E0");

	Params::BP_Item_Pistol_C_OnBlendOut_7FFB8CC54B246D4BCE5C6CAEFFF1B0E0 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.OnBlendOut_832518624257BAE274FFBFB954633F02
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::OnBlendOut_832518624257BAE274FFBFB954633F02(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "OnBlendOut_832518624257BAE274FFBFB954633F02");

	Params::BP_Item_Pistol_C_OnBlendOut_832518624257BAE274FFBFB954633F02 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.OnBlendOut_A1966B1E4239D5D9E79D29880EDA1BA9
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::OnBlendOut_A1966B1E4239D5D9E79D29880EDA1BA9(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "OnBlendOut_A1966B1E4239D5D9E79D29880EDA1BA9");

	Params::BP_Item_Pistol_C_OnBlendOut_A1966B1E4239D5D9E79D29880EDA1BA9 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.OnBlendOut_B6239810407E3940DB6B3380427E8EF6
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::OnBlendOut_B6239810407E3940DB6B3380427E8EF6(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "OnBlendOut_B6239810407E3940DB6B3380427E8EF6");

	Params::BP_Item_Pistol_C_OnBlendOut_B6239810407E3940DB6B3380427E8EF6 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.OnBlendOut_C489C4444F267A9BBAE7599B57430D6F
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::OnBlendOut_C489C4444F267A9BBAE7599B57430D6F(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "OnBlendOut_C489C4444F267A9BBAE7599B57430D6F");

	Params::BP_Item_Pistol_C_OnBlendOut_C489C4444F267A9BBAE7599B57430D6F Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.OnBlendOut_C636BF3B47DA6BD2B8E32FAF8899289D
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::OnBlendOut_C636BF3B47DA6BD2B8E32FAF8899289D(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "OnBlendOut_C636BF3B47DA6BD2B8E32FAF8899289D");

	Params::BP_Item_Pistol_C_OnBlendOut_C636BF3B47DA6BD2B8E32FAF8899289D Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.OnBlendOut_F4B3245C4CD17DE6B70CC196353A25B3
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::OnBlendOut_F4B3245C4CD17DE6B70CC196353A25B3(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "OnBlendOut_F4B3245C4CD17DE6B70CC196353A25B3");

	Params::BP_Item_Pistol_C_OnBlendOut_F4B3245C4CD17DE6B70CC196353A25B3 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.OnBlendOut_F57095504E4F315F4ADA7FB9A5E14FD7
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::OnBlendOut_F57095504E4F315F4ADA7FB9A5E14FD7(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "OnBlendOut_F57095504E4F315F4ADA7FB9A5E14FD7");

	Params::BP_Item_Pistol_C_OnBlendOut_F57095504E4F315F4ADA7FB9A5E14FD7 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.OnCompleted_1966F0C0404D446918EDC1BA9E0AE10D
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::OnCompleted_1966F0C0404D446918EDC1BA9E0AE10D(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "OnCompleted_1966F0C0404D446918EDC1BA9E0AE10D");

	Params::BP_Item_Pistol_C_OnCompleted_1966F0C0404D446918EDC1BA9E0AE10D Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.OnCompleted_28B7E75842493FF7C0642EAD62EAAE5B
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::OnCompleted_28B7E75842493FF7C0642EAD62EAAE5B(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "OnCompleted_28B7E75842493FF7C0642EAD62EAAE5B");

	Params::BP_Item_Pistol_C_OnCompleted_28B7E75842493FF7C0642EAD62EAAE5B Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.OnCompleted_2F55E14E4CDE96EBB3363BA5C7B412AB
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::OnCompleted_2F55E14E4CDE96EBB3363BA5C7B412AB(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "OnCompleted_2F55E14E4CDE96EBB3363BA5C7B412AB");

	Params::BP_Item_Pistol_C_OnCompleted_2F55E14E4CDE96EBB3363BA5C7B412AB Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.OnCompleted_45E13C734FB393DCFAE5ABB5CC9473FB
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::OnCompleted_45E13C734FB393DCFAE5ABB5CC9473FB(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "OnCompleted_45E13C734FB393DCFAE5ABB5CC9473FB");

	Params::BP_Item_Pistol_C_OnCompleted_45E13C734FB393DCFAE5ABB5CC9473FB Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.OnCompleted_630B46B841FC7C8FC0E1CBA4A9E2190F
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::OnCompleted_630B46B841FC7C8FC0E1CBA4A9E2190F(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "OnCompleted_630B46B841FC7C8FC0E1CBA4A9E2190F");

	Params::BP_Item_Pistol_C_OnCompleted_630B46B841FC7C8FC0E1CBA4A9E2190F Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.OnCompleted_7BD1D9B44937E94B4C7143A26722060F
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::OnCompleted_7BD1D9B44937E94B4C7143A26722060F(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "OnCompleted_7BD1D9B44937E94B4C7143A26722060F");

	Params::BP_Item_Pistol_C_OnCompleted_7BD1D9B44937E94B4C7143A26722060F Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.OnCompleted_7FFB8CC54B246D4BCE5C6CAEFFF1B0E0
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::OnCompleted_7FFB8CC54B246D4BCE5C6CAEFFF1B0E0(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "OnCompleted_7FFB8CC54B246D4BCE5C6CAEFFF1B0E0");

	Params::BP_Item_Pistol_C_OnCompleted_7FFB8CC54B246D4BCE5C6CAEFFF1B0E0 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.OnCompleted_832518624257BAE274FFBFB954633F02
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::OnCompleted_832518624257BAE274FFBFB954633F02(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "OnCompleted_832518624257BAE274FFBFB954633F02");

	Params::BP_Item_Pistol_C_OnCompleted_832518624257BAE274FFBFB954633F02 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.OnCompleted_A1966B1E4239D5D9E79D29880EDA1BA9
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::OnCompleted_A1966B1E4239D5D9E79D29880EDA1BA9(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "OnCompleted_A1966B1E4239D5D9E79D29880EDA1BA9");

	Params::BP_Item_Pistol_C_OnCompleted_A1966B1E4239D5D9E79D29880EDA1BA9 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.OnCompleted_B6239810407E3940DB6B3380427E8EF6
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::OnCompleted_B6239810407E3940DB6B3380427E8EF6(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "OnCompleted_B6239810407E3940DB6B3380427E8EF6");

	Params::BP_Item_Pistol_C_OnCompleted_B6239810407E3940DB6B3380427E8EF6 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.OnCompleted_C489C4444F267A9BBAE7599B57430D6F
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::OnCompleted_C489C4444F267A9BBAE7599B57430D6F(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "OnCompleted_C489C4444F267A9BBAE7599B57430D6F");

	Params::BP_Item_Pistol_C_OnCompleted_C489C4444F267A9BBAE7599B57430D6F Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.OnCompleted_C636BF3B47DA6BD2B8E32FAF8899289D
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::OnCompleted_C636BF3B47DA6BD2B8E32FAF8899289D(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "OnCompleted_C636BF3B47DA6BD2B8E32FAF8899289D");

	Params::BP_Item_Pistol_C_OnCompleted_C636BF3B47DA6BD2B8E32FAF8899289D Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.OnCompleted_F4B3245C4CD17DE6B70CC196353A25B3
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::OnCompleted_F4B3245C4CD17DE6B70CC196353A25B3(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "OnCompleted_F4B3245C4CD17DE6B70CC196353A25B3");

	Params::BP_Item_Pistol_C_OnCompleted_F4B3245C4CD17DE6B70CC196353A25B3 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.OnCompleted_F57095504E4F315F4ADA7FB9A5E14FD7
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::OnCompleted_F57095504E4F315F4ADA7FB9A5E14FD7(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "OnCompleted_F57095504E4F315F4ADA7FB9A5E14FD7");

	Params::BP_Item_Pistol_C_OnCompleted_F57095504E4F315F4ADA7FB9A5E14FD7 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.OnInterrupted_1966F0C0404D446918EDC1BA9E0AE10D
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::OnInterrupted_1966F0C0404D446918EDC1BA9E0AE10D(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "OnInterrupted_1966F0C0404D446918EDC1BA9E0AE10D");

	Params::BP_Item_Pistol_C_OnInterrupted_1966F0C0404D446918EDC1BA9E0AE10D Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.OnInterrupted_28B7E75842493FF7C0642EAD62EAAE5B
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::OnInterrupted_28B7E75842493FF7C0642EAD62EAAE5B(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "OnInterrupted_28B7E75842493FF7C0642EAD62EAAE5B");

	Params::BP_Item_Pistol_C_OnInterrupted_28B7E75842493FF7C0642EAD62EAAE5B Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.OnInterrupted_2F55E14E4CDE96EBB3363BA5C7B412AB
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::OnInterrupted_2F55E14E4CDE96EBB3363BA5C7B412AB(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "OnInterrupted_2F55E14E4CDE96EBB3363BA5C7B412AB");

	Params::BP_Item_Pistol_C_OnInterrupted_2F55E14E4CDE96EBB3363BA5C7B412AB Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.OnInterrupted_45E13C734FB393DCFAE5ABB5CC9473FB
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::OnInterrupted_45E13C734FB393DCFAE5ABB5CC9473FB(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "OnInterrupted_45E13C734FB393DCFAE5ABB5CC9473FB");

	Params::BP_Item_Pistol_C_OnInterrupted_45E13C734FB393DCFAE5ABB5CC9473FB Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.OnInterrupted_630B46B841FC7C8FC0E1CBA4A9E2190F
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::OnInterrupted_630B46B841FC7C8FC0E1CBA4A9E2190F(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "OnInterrupted_630B46B841FC7C8FC0E1CBA4A9E2190F");

	Params::BP_Item_Pistol_C_OnInterrupted_630B46B841FC7C8FC0E1CBA4A9E2190F Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.OnInterrupted_7BD1D9B44937E94B4C7143A26722060F
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::OnInterrupted_7BD1D9B44937E94B4C7143A26722060F(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "OnInterrupted_7BD1D9B44937E94B4C7143A26722060F");

	Params::BP_Item_Pistol_C_OnInterrupted_7BD1D9B44937E94B4C7143A26722060F Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.OnInterrupted_7FFB8CC54B246D4BCE5C6CAEFFF1B0E0
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::OnInterrupted_7FFB8CC54B246D4BCE5C6CAEFFF1B0E0(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "OnInterrupted_7FFB8CC54B246D4BCE5C6CAEFFF1B0E0");

	Params::BP_Item_Pistol_C_OnInterrupted_7FFB8CC54B246D4BCE5C6CAEFFF1B0E0 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.OnInterrupted_832518624257BAE274FFBFB954633F02
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::OnInterrupted_832518624257BAE274FFBFB954633F02(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "OnInterrupted_832518624257BAE274FFBFB954633F02");

	Params::BP_Item_Pistol_C_OnInterrupted_832518624257BAE274FFBFB954633F02 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.OnInterrupted_A1966B1E4239D5D9E79D29880EDA1BA9
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::OnInterrupted_A1966B1E4239D5D9E79D29880EDA1BA9(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "OnInterrupted_A1966B1E4239D5D9E79D29880EDA1BA9");

	Params::BP_Item_Pistol_C_OnInterrupted_A1966B1E4239D5D9E79D29880EDA1BA9 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.OnInterrupted_B6239810407E3940DB6B3380427E8EF6
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::OnInterrupted_B6239810407E3940DB6B3380427E8EF6(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "OnInterrupted_B6239810407E3940DB6B3380427E8EF6");

	Params::BP_Item_Pistol_C_OnInterrupted_B6239810407E3940DB6B3380427E8EF6 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.OnInterrupted_C489C4444F267A9BBAE7599B57430D6F
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::OnInterrupted_C489C4444F267A9BBAE7599B57430D6F(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "OnInterrupted_C489C4444F267A9BBAE7599B57430D6F");

	Params::BP_Item_Pistol_C_OnInterrupted_C489C4444F267A9BBAE7599B57430D6F Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.OnInterrupted_C636BF3B47DA6BD2B8E32FAF8899289D
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::OnInterrupted_C636BF3B47DA6BD2B8E32FAF8899289D(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "OnInterrupted_C636BF3B47DA6BD2B8E32FAF8899289D");

	Params::BP_Item_Pistol_C_OnInterrupted_C636BF3B47DA6BD2B8E32FAF8899289D Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.OnInterrupted_F4B3245C4CD17DE6B70CC196353A25B3
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::OnInterrupted_F4B3245C4CD17DE6B70CC196353A25B3(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "OnInterrupted_F4B3245C4CD17DE6B70CC196353A25B3");

	Params::BP_Item_Pistol_C_OnInterrupted_F4B3245C4CD17DE6B70CC196353A25B3 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.OnInterrupted_F57095504E4F315F4ADA7FB9A5E14FD7
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::OnInterrupted_F57095504E4F315F4ADA7FB9A5E14FD7(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "OnInterrupted_F57095504E4F315F4ADA7FB9A5E14FD7");

	Params::BP_Item_Pistol_C_OnInterrupted_F57095504E4F315F4ADA7FB9A5E14FD7 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.OnNotifyBegin_1966F0C0404D446918EDC1BA9E0AE10D
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::OnNotifyBegin_1966F0C0404D446918EDC1BA9E0AE10D(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "OnNotifyBegin_1966F0C0404D446918EDC1BA9E0AE10D");

	Params::BP_Item_Pistol_C_OnNotifyBegin_1966F0C0404D446918EDC1BA9E0AE10D Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.OnNotifyBegin_28B7E75842493FF7C0642EAD62EAAE5B
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::OnNotifyBegin_28B7E75842493FF7C0642EAD62EAAE5B(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "OnNotifyBegin_28B7E75842493FF7C0642EAD62EAAE5B");

	Params::BP_Item_Pistol_C_OnNotifyBegin_28B7E75842493FF7C0642EAD62EAAE5B Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.OnNotifyBegin_2F55E14E4CDE96EBB3363BA5C7B412AB
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::OnNotifyBegin_2F55E14E4CDE96EBB3363BA5C7B412AB(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "OnNotifyBegin_2F55E14E4CDE96EBB3363BA5C7B412AB");

	Params::BP_Item_Pistol_C_OnNotifyBegin_2F55E14E4CDE96EBB3363BA5C7B412AB Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.OnNotifyBegin_45E13C734FB393DCFAE5ABB5CC9473FB
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::OnNotifyBegin_45E13C734FB393DCFAE5ABB5CC9473FB(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "OnNotifyBegin_45E13C734FB393DCFAE5ABB5CC9473FB");

	Params::BP_Item_Pistol_C_OnNotifyBegin_45E13C734FB393DCFAE5ABB5CC9473FB Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.OnNotifyBegin_630B46B841FC7C8FC0E1CBA4A9E2190F
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::OnNotifyBegin_630B46B841FC7C8FC0E1CBA4A9E2190F(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "OnNotifyBegin_630B46B841FC7C8FC0E1CBA4A9E2190F");

	Params::BP_Item_Pistol_C_OnNotifyBegin_630B46B841FC7C8FC0E1CBA4A9E2190F Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.OnNotifyBegin_7BD1D9B44937E94B4C7143A26722060F
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::OnNotifyBegin_7BD1D9B44937E94B4C7143A26722060F(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "OnNotifyBegin_7BD1D9B44937E94B4C7143A26722060F");

	Params::BP_Item_Pistol_C_OnNotifyBegin_7BD1D9B44937E94B4C7143A26722060F Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.OnNotifyBegin_7FFB8CC54B246D4BCE5C6CAEFFF1B0E0
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::OnNotifyBegin_7FFB8CC54B246D4BCE5C6CAEFFF1B0E0(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "OnNotifyBegin_7FFB8CC54B246D4BCE5C6CAEFFF1B0E0");

	Params::BP_Item_Pistol_C_OnNotifyBegin_7FFB8CC54B246D4BCE5C6CAEFFF1B0E0 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.OnNotifyBegin_832518624257BAE274FFBFB954633F02
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::OnNotifyBegin_832518624257BAE274FFBFB954633F02(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "OnNotifyBegin_832518624257BAE274FFBFB954633F02");

	Params::BP_Item_Pistol_C_OnNotifyBegin_832518624257BAE274FFBFB954633F02 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.OnNotifyBegin_A1966B1E4239D5D9E79D29880EDA1BA9
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::OnNotifyBegin_A1966B1E4239D5D9E79D29880EDA1BA9(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "OnNotifyBegin_A1966B1E4239D5D9E79D29880EDA1BA9");

	Params::BP_Item_Pistol_C_OnNotifyBegin_A1966B1E4239D5D9E79D29880EDA1BA9 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.OnNotifyBegin_B6239810407E3940DB6B3380427E8EF6
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::OnNotifyBegin_B6239810407E3940DB6B3380427E8EF6(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "OnNotifyBegin_B6239810407E3940DB6B3380427E8EF6");

	Params::BP_Item_Pistol_C_OnNotifyBegin_B6239810407E3940DB6B3380427E8EF6 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.OnNotifyBegin_C489C4444F267A9BBAE7599B57430D6F
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::OnNotifyBegin_C489C4444F267A9BBAE7599B57430D6F(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "OnNotifyBegin_C489C4444F267A9BBAE7599B57430D6F");

	Params::BP_Item_Pistol_C_OnNotifyBegin_C489C4444F267A9BBAE7599B57430D6F Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.OnNotifyBegin_C636BF3B47DA6BD2B8E32FAF8899289D
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::OnNotifyBegin_C636BF3B47DA6BD2B8E32FAF8899289D(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "OnNotifyBegin_C636BF3B47DA6BD2B8E32FAF8899289D");

	Params::BP_Item_Pistol_C_OnNotifyBegin_C636BF3B47DA6BD2B8E32FAF8899289D Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.OnNotifyBegin_F4B3245C4CD17DE6B70CC196353A25B3
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::OnNotifyBegin_F4B3245C4CD17DE6B70CC196353A25B3(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "OnNotifyBegin_F4B3245C4CD17DE6B70CC196353A25B3");

	Params::BP_Item_Pistol_C_OnNotifyBegin_F4B3245C4CD17DE6B70CC196353A25B3 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.OnNotifyBegin_F57095504E4F315F4ADA7FB9A5E14FD7
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::OnNotifyBegin_F57095504E4F315F4ADA7FB9A5E14FD7(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "OnNotifyBegin_F57095504E4F315F4ADA7FB9A5E14FD7");

	Params::BP_Item_Pistol_C_OnNotifyBegin_F57095504E4F315F4ADA7FB9A5E14FD7 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.OnNotifyEnd_1966F0C0404D446918EDC1BA9E0AE10D
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::OnNotifyEnd_1966F0C0404D446918EDC1BA9E0AE10D(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "OnNotifyEnd_1966F0C0404D446918EDC1BA9E0AE10D");

	Params::BP_Item_Pistol_C_OnNotifyEnd_1966F0C0404D446918EDC1BA9E0AE10D Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.OnNotifyEnd_28B7E75842493FF7C0642EAD62EAAE5B
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::OnNotifyEnd_28B7E75842493FF7C0642EAD62EAAE5B(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "OnNotifyEnd_28B7E75842493FF7C0642EAD62EAAE5B");

	Params::BP_Item_Pistol_C_OnNotifyEnd_28B7E75842493FF7C0642EAD62EAAE5B Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.OnNotifyEnd_2F55E14E4CDE96EBB3363BA5C7B412AB
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::OnNotifyEnd_2F55E14E4CDE96EBB3363BA5C7B412AB(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "OnNotifyEnd_2F55E14E4CDE96EBB3363BA5C7B412AB");

	Params::BP_Item_Pistol_C_OnNotifyEnd_2F55E14E4CDE96EBB3363BA5C7B412AB Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.OnNotifyEnd_45E13C734FB393DCFAE5ABB5CC9473FB
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::OnNotifyEnd_45E13C734FB393DCFAE5ABB5CC9473FB(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "OnNotifyEnd_45E13C734FB393DCFAE5ABB5CC9473FB");

	Params::BP_Item_Pistol_C_OnNotifyEnd_45E13C734FB393DCFAE5ABB5CC9473FB Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.OnNotifyEnd_630B46B841FC7C8FC0E1CBA4A9E2190F
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::OnNotifyEnd_630B46B841FC7C8FC0E1CBA4A9E2190F(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "OnNotifyEnd_630B46B841FC7C8FC0E1CBA4A9E2190F");

	Params::BP_Item_Pistol_C_OnNotifyEnd_630B46B841FC7C8FC0E1CBA4A9E2190F Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.OnNotifyEnd_7BD1D9B44937E94B4C7143A26722060F
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::OnNotifyEnd_7BD1D9B44937E94B4C7143A26722060F(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "OnNotifyEnd_7BD1D9B44937E94B4C7143A26722060F");

	Params::BP_Item_Pistol_C_OnNotifyEnd_7BD1D9B44937E94B4C7143A26722060F Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.OnNotifyEnd_7FFB8CC54B246D4BCE5C6CAEFFF1B0E0
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::OnNotifyEnd_7FFB8CC54B246D4BCE5C6CAEFFF1B0E0(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "OnNotifyEnd_7FFB8CC54B246D4BCE5C6CAEFFF1B0E0");

	Params::BP_Item_Pistol_C_OnNotifyEnd_7FFB8CC54B246D4BCE5C6CAEFFF1B0E0 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.OnNotifyEnd_832518624257BAE274FFBFB954633F02
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::OnNotifyEnd_832518624257BAE274FFBFB954633F02(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "OnNotifyEnd_832518624257BAE274FFBFB954633F02");

	Params::BP_Item_Pistol_C_OnNotifyEnd_832518624257BAE274FFBFB954633F02 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.OnNotifyEnd_A1966B1E4239D5D9E79D29880EDA1BA9
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::OnNotifyEnd_A1966B1E4239D5D9E79D29880EDA1BA9(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "OnNotifyEnd_A1966B1E4239D5D9E79D29880EDA1BA9");

	Params::BP_Item_Pistol_C_OnNotifyEnd_A1966B1E4239D5D9E79D29880EDA1BA9 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.OnNotifyEnd_B6239810407E3940DB6B3380427E8EF6
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::OnNotifyEnd_B6239810407E3940DB6B3380427E8EF6(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "OnNotifyEnd_B6239810407E3940DB6B3380427E8EF6");

	Params::BP_Item_Pistol_C_OnNotifyEnd_B6239810407E3940DB6B3380427E8EF6 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.OnNotifyEnd_C489C4444F267A9BBAE7599B57430D6F
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::OnNotifyEnd_C489C4444F267A9BBAE7599B57430D6F(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "OnNotifyEnd_C489C4444F267A9BBAE7599B57430D6F");

	Params::BP_Item_Pistol_C_OnNotifyEnd_C489C4444F267A9BBAE7599B57430D6F Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.OnNotifyEnd_C636BF3B47DA6BD2B8E32FAF8899289D
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::OnNotifyEnd_C636BF3B47DA6BD2B8E32FAF8899289D(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "OnNotifyEnd_C636BF3B47DA6BD2B8E32FAF8899289D");

	Params::BP_Item_Pistol_C_OnNotifyEnd_C636BF3B47DA6BD2B8E32FAF8899289D Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.OnNotifyEnd_F4B3245C4CD17DE6B70CC196353A25B3
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::OnNotifyEnd_F4B3245C4CD17DE6B70CC196353A25B3(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "OnNotifyEnd_F4B3245C4CD17DE6B70CC196353A25B3");

	Params::BP_Item_Pistol_C_OnNotifyEnd_F4B3245C4CD17DE6B70CC196353A25B3 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.OnNotifyEnd_F57095504E4F315F4ADA7FB9A5E14FD7
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_Pistol_C::OnNotifyEnd_F57095504E4F315F4ADA7FB9A5E14FD7(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "OnNotifyEnd_F57095504E4F315F4ADA7FB9A5E14FD7");

	Params::BP_Item_Pistol_C_OnNotifyEnd_F57095504E4F315F4ADA7FB9A5E14FD7 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_Pistol.BP_Item_Pistol_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_Item_Pistol_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_Pistol_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

