#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Item_Spell_Thrower

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_Item_Spell_Thrower.BP_Item_Spell_Thrower_C.ExecuteUbergraph_BP_Item_Spell_Thrower
// 0x0008 (0x0008 - 0x0000)
struct BP_Item_Spell_Thrower_C_ExecuteUbergraph_BP_Item_Spell_Thrower final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsLocallyControlled_ReturnValue;          // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_Item_Spell_Thrower_C_ExecuteUbergraph_BP_Item_Spell_Thrower;

}

