#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Map_Area41

#include "Basic.hpp"

#include "BP_Map_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Map_Area41.BP_Map_Area41_C
// 0x0000 (0x02F8 - 0x02F8)
class ABP_Map_Area41_C final : public ABP_Map_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Map_Area41_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Map_Area41_C")
	}
	static class ABP_Map_Area41_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Map_Area41_C>();
	}
};
DUMPER7_ASSERTS_ABP_Map_Area41_C;

}

