#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_NPC

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "CoreUObject_structs.hpp"
#include "AIModule_structs.hpp"
#include "E_DamageCategory_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_NPC.BP_NPC_C
// 0x0140 (0x0790 - 0x0650)
#pragma pack(push, 0x1)
class alignas(0x10) ABP_NPC_C : public ACharacter
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0650(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UAC_SkeletalMeshOptimizer_C*            AC_SkeletalMeshOptimizer;                          // 0x0658(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          Box;                                               // 0x0660(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UWidgetComponent*                       Widget;                                            // 0x0668(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UArrowComponent*                        Socket_Shoot;                                      // 0x0670(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMesh;                                        // 0x0678(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	float                                         T_RotateToTarget_Alpha_B12ECBCF4994BD697E75C4BEFE3A5BF7; // 0x0680(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            T_RotateToTarget__Direction_B12ECBCF4994BD697E75C4BEFE3A5BF7; // 0x0684(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_685[0x3];                                      // 0x0685(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     T_RotateToTarget;                                  // 0x0688(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	float                                         T_Rotate_Alpha_B1ACFA7F439182777F86B199A5628CF3;   // 0x0690(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            T_Rotate__Direction_B1ACFA7F439182777F86B199A5628CF3; // 0x0694(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_695[0x3];                                      // 0x0695(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     T_Rotate;                                          // 0x0698(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 TalkingCharacter;                                  // 0x06A0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class FText                                   NpcName;                                           // 0x06A8(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                          Enabled;                                           // 0x06B8(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash)
	bool                                          hasWeapon;                                         // 0x06B9(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_6BA[0x6];                                      // 0x06BA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        headHeightOffset;                                  // 0x06C0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAnimMontage*                           Montage;                                           // 0x06C8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          canMove;                                           // 0x06D0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          canShoot;                                          // 0x06D1(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_6D2[0x6];                                      // 0x06D2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FRotator                               preRotationRotation;                               // 0x06D8(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	struct FRotator                               postRotationRotation;                              // 0x06F0(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	class UClass*                                 Questline;                                         // 0x0708(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  lookedAtPlayer;                                    // 0x0710(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                          shownNameRuntime;                                  // 0x0718(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash)
	bool                                          noClipMode;                                        // 0x0719(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_71A[0x6];                                      // 0x071A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   uiDescriptionText;                                 // 0x0720(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                          justShotAtEnemy;                                   // 0x0730(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_731[0x7];                                      // 0x0731(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 targetedEnemy;                                     // 0x0738(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                          skeletalMeshOptimization;                          // 0x0740(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_741[0x7];                                      // 0x0741(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FRotator                               startRotationTarget;                               // 0x0748(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	struct FRotator                               deisredNewRotationTarget;                          // 0x0760(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	double                                        maximumCamLookAtDistance;                          // 0x0778(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          isBoxDisabled;                                     // 0x0780(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash)

public:
	void F_GetShootAtLoc(bool* Found, struct FVector* Loc, class USceneComponent** SceneComponent);
	void F_CanBeAutoAimed(bool* CanBeAutoAimed, struct FVector* autoAimedLocation);
	void F_PingObject(bool* canBePinged, class UClass** pingActor, class FText* ChatLine, class USceneComponent** AttachedComponent);
	void F_GetInteractableDatas(struct FS_InteractableDatas* InteractableDatas);
	void F_GetBuffs(bool* Found, TArray<class UClass*>* BuffObjects);
	void F_HitMarkerRequest(bool Critical, bool* Receive);
	void OnRep_isBoxDisabled();
	void F_FindEnemy();
	void OnRep_shownNameRuntime();
	void F_InitWidget();
	void F_InitQuest();
	void F_ShootAtNearestEnemy();
	void F_ShootSingleBulet();
	void OnRep_enabled();
	void UserConstructionScript();
	void T_Rotate__FinishedFunc();
	void T_Rotate__UpdateFunc();
	void T_RotateToTarget__FinishedFunc();
	void T_RotateToTarget__UpdateFunc();
	void OnFail_0C19B8C34C119C0C679D29A88F7FD311(EPathFollowingResult MovementResult);
	void OnSuccess_0C19B8C34C119C0C679D29A88F7FD311(EPathFollowingResult MovementResult);
	void OnNotifyEnd_51AAB1354C0E75766D4A1FB31A69B698(class FName NotifyName);
	void OnNotifyBegin_51AAB1354C0E75766D4A1FB31A69B698(class FName NotifyName);
	void OnInterrupted_51AAB1354C0E75766D4A1FB31A69B698(class FName NotifyName);
	void OnBlendOut_51AAB1354C0E75766D4A1FB31A69B698(class FName NotifyName);
	void OnCompleted_51AAB1354C0E75766D4A1FB31A69B698(class FName NotifyName);
	void OnNotifyEnd_F3189A0C4C3419DB4700F8AAB97369EC(class FName NotifyName);
	void OnNotifyBegin_F3189A0C4C3419DB4700F8AAB97369EC(class FName NotifyName);
	void OnInterrupted_F3189A0C4C3419DB4700F8AAB97369EC(class FName NotifyName);
	void OnBlendOut_F3189A0C4C3419DB4700F8AAB97369EC(class FName NotifyName);
	void OnCompleted_F3189A0C4C3419DB4700F8AAB97369EC(class FName NotifyName);
	void F_DamageFeedback(const struct FHitResult& Hit, class AActor* Owner_0, double Damages, class UClass* DamageType, bool Critical, E_DamageCategory Element, class FName ItemName);
	void F_HoverInteract();
	void F_Activate(int32 Wildcard, double Delay, class AActor* Owner_0);
	void F_ReceiveBuff(class AActor* Owner_0, const struct FVector& ReceivedLoc, class UClass* BuffObject);
	void F_KillCombo();
	void F_Channel(class AActor* ChannelingOwner, int32 Wildcard);
	void F_StopChannel(class AActor* ChannelingActor);
	void F_AddImpulseServer(const struct FVector& HitNormal, const struct FVector& Location);
	void F_StartPhysic(class UPrimitiveComponent* Component, const struct FVector& HitLoc, const struct FVector& Normal, double Strenght, class AActor* hitOwner, E_DamageCategory DamageCategory);
	void F_Bounce(const struct FVector& DirectionAxis, const struct FVector& BounceLoc);
	void F_SetAttachedActor(class AActor* AttachedActor);
	void F_StopInteract(class AActor* Owner_0);
	void F_Activate_Location(const struct FVector& Location, class AActor* Owner_0, int32 Wildcard, class UPrimitiveComponent* Component);
	void F_SendUnlockables(const TArray<class UClass*>& Unlockables);
	void F_TriggerTalisman(class ABP_Item_C* Item, class AActor* WildClassActor);
	void F_StartInteract(class AActor* Owner_0);
	void F_SetCustomMaterialParameter(class FName Param, double Value);
	void F_QuestProgress(class FName Tag);
	void F_EventAlert();
	void F_RemoveBuff(class UClass* BuffObject);
	void F_SetCanBeDestroyedIfNoPlayerAround();
	void F_ServerDamages(double Damages, class UClass* DamageType, class AActor* Causer, E_DamageCategory Element, class FName ItemName);
	void F_PassWildcard(int32 Wildcard);
	void F_ServerExplosion(class FName ExplosionName, double Damages, class AActor* Causer);
	void F_SpawnNiagaraSystemOnEnemy(class UNiagaraSystem* System);
	void F_RemoveNiagaraSystemOnEnemy(class UNiagaraSystem* System);
	void F_BuffManagerClearBuffFromActor(class UClass* Buff);
	void ReceiveBeginPlay();
	void F_FollowPlayer();
	void F_Interact(class AActor* Owner_0, int32 Wildcard);
	void F_RotateToWorldRotation(const struct FRotator& NewRotation);
	void F_Montage_Multicast(class UAnimMontage* MontageToPlay);
	void F_StartWork(class AActor* Actor);
	void F_Shoot();
	void F_StopFollowPlayer();
	void F_RotateToTargetOverTime(double Duration, const struct FRotator& deisredNewRotationTarget_0);
	void ExecuteUbergraph_BP_NPC(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_NPC_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_NPC_C")
	}
	static class ABP_NPC_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_NPC_C>();
	}
};
#pragma pack(pop)
DUMPER7_ASSERTS_ABP_NPC_C;

}

