#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Pickable_Canyon_Amulet_GoldNugget

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "S_InteractableDatas_structs.hpp"


namespace SDK::Params
{

// Function BP_Pickable_Canyon_Amulet_GoldNugget.BP_Pickable_Canyon_Amulet_GoldNugget_C.ExecuteUbergraph_BP_Pickable_Canyon_Amulet_GoldNugget
// 0x0038 (0x0038 - 0x0000)
struct BP_Pickable_Canyon_Amulet_GoldNugget_C_ExecuteUbergraph_BP_Pickable_Canyon_Amulet_GoldNugget final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0004(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_GetAttachParentActor_ReturnValue;         // 0x0018(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_Canyon_DigHole_Amulette_GoldNugget_C* K2Node_DynamicCast_AsBP_Canyon_Dig_Hole_Amulette_Gold_Nugget; // 0x0028(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_Pickable_Canyon_Amulet_GoldNugget_C_ExecuteUbergraph_BP_Pickable_Canyon_Amulet_GoldNugget;

// Function BP_Pickable_Canyon_Amulet_GoldNugget.BP_Pickable_Canyon_Amulet_GoldNugget_C.F_GetInteractableDatas
// 0x0080 (0x0080 - 0x0000)
struct BP_Pickable_Canyon_Amulet_GoldNugget_C_F_GetInteractableDatas final
{
public:
	struct FS_InteractableDatas                   InteractableDatas;                                 // 0x0000(0x0040)(Parm, OutParm, HasGetValueTypeHash)
	struct FS_InteractableDatas                   K2Node_MakeStruct_S_InteractableDatas;             // 0x0040(0x0040)(HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_Pickable_Canyon_Amulet_GoldNugget_C_F_GetInteractableDatas;

// Function BP_Pickable_Canyon_Amulet_GoldNugget.BP_Pickable_Canyon_Amulet_GoldNugget_C.OnRep_DirtyCanBePicked
// 0x0004 (0x0004 - 0x0000)
struct BP_Pickable_Canyon_Amulet_GoldNugget_C_OnRep_DirtyCanBePicked final
{
public:
	bool                                          Temp_bool_Variable;                                // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ECollisionEnabled                             Temp_byte_Variable;                                // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ECollisionEnabled                             Temp_byte_Variable_1;                              // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ECollisionEnabled                             K2Node_Select_Default;                             // 0x0003(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_Pickable_Canyon_Amulet_GoldNugget_C_OnRep_DirtyCanBePicked;

}

