#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Ping_Extraction

#include "Basic.hpp"

#include "BP_Ping_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Ping_Extraction.BP_Ping_Extraction_C
// 0x0000 (0x0320 - 0x0320)
class ABP_Ping_Extraction_C final : public ABP_Ping_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Ping_Extraction_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Ping_Extraction_C")
	}
	static class ABP_Ping_Extraction_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Ping_Extraction_C>();
	}
};
DUMPER7_ASSERTS_ABP_Ping_Extraction_C;

}

