#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PickableShovel_PlayerDropped

#include "Basic.hpp"

#include "BP_PickableShovel_PlayerDropped_classes.hpp"
#include "BP_PickableShovel_PlayerDropped_parameters.hpp"


namespace SDK
{

// Function BP_PickableShovel_PlayerDropped.BP_PickableShovel_PlayerDropped_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_PickableShovel_PlayerDropped_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PickableShovel_PlayerDropped_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PickableShovel_PlayerDropped.BP_PickableShovel_PlayerDropped_C.ExecuteUbergraph_BP_PickableShovel_PlayerDropped
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_PickableShovel_PlayerDropped_C::ExecuteUbergraph_BP_PickableShovel_PlayerDropped(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PickableShovel_PlayerDropped_C", "ExecuteUbergraph_BP_PickableShovel_PlayerDropped");

	Params::BP_PickableShovel_PlayerDropped_C_ExecuteUbergraph_BP_PickableShovel_PlayerDropped Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

