#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Pickable_Downloader_PlayerDropped

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_Pickable_Downloader_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Pickable_Downloader_PlayerDropped.BP_Pickable_Downloader_PlayerDropped_C
// 0x0008 (0x02E8 - 0x02E0)
class ABP_Pickable_Downloader_PlayerDropped_C final : public ABP_Pickable_Downloader_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_Pickable_Downloader_PlayerDropped_C; // 0x02E0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BP_Pickable_Downloader_PlayerDropped(int32 EntryPoint);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Pickable_Downloader_PlayerDropped_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Pickable_Downloader_PlayerDropped_C")
	}
	static class ABP_Pickable_Downloader_PlayerDropped_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Pickable_Downloader_PlayerDropped_C>();
	}
};
DUMPER7_ASSERTS_ABP_Pickable_Downloader_PlayerDropped_C;

}

