#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_POI_B

#include "Basic.hpp"

#include "BP_InterestPoint_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_POI_B.BP_POI_B_C
// 0x0000 (0x02E8 - 0x02E8)
class ABP_POI_B_C final : public ABP_InterestPoint_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_POI_B_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_POI_B_C")
	}
	static class ABP_POI_B_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_POI_B_C>();
	}
};
DUMPER7_ASSERTS_ABP_POI_B_C;

}

