#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PhysicObject

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "CoreUObject_structs.hpp"
#include "E_DamageCategory_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_PhysicObject.BP_PhysicObject_C
// 0x00A8 (0x0358 - 0x02B0)
class ABP_PhysicObject_C : public AActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02B0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UStaticMeshComponent*                   StaticMesh;                                        // 0x02B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        Scene;                                             // 0x02C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	TArray<class UPrimitiveComponent*>            hitComponents;                                     // 0x02C8(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	float                                         physicImpulseMultiplier;                           // 0x02D8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         angularImpulseForce;                               // 0x02DC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class UMeshComponent*>                 Meshes;                                            // 0x02E0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	bool                                          propagateImpulseToAllMeshes;                       // 0x02F0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          physicConstantlyEnabled;                           // 0x02F1(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2F2[0x6];                                      // 0x02F2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void(class AActor* Owner)> disp_PlayerHitLocal;                         // 0x02F8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	class USoundBase*                             impactSound;                                       // 0x0308(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	double                                        soundThreshold;                                    // 0x0310(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          canReceiveHits;                                    // 0x0318(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          playerCloseEnough;                                 // 0x0319(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_31A[0x2];                                      // 0x031A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         distanceToPlayer;                                  // 0x031C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         MaxDrawDistance;                                   // 0x0320(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_324[0x4];                                      // 0x0324(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                initialObjectOrigin;                               // 0x0328(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                initialBoxExtend;                                  // 0x0340(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void F_GetShootAtLoc(bool* Found, struct FVector* Loc, class USceneComponent** SceneComponent);
	void F_CanBeAutoAimed(bool* CanBeAutoAimed, struct FVector* autoAimedLocation);
	void F_PingObject(bool* canBePinged, class UClass** pingActor, class FText* ChatLine, class USceneComponent** AttachedComponent);
	void F_GetInteractableDatas(struct FS_InteractableDatas* InteractableDatas);
	void F_GetBuffs(bool* Found, TArray<class UClass*>* BuffObjects);
	void F_HitMarkerRequest(bool Critical, bool* Receive);
	void F_OptimizeLights();
	void F_ImpulsePhysicObjectAbove(class AActor* hitOwner);
	void F_MeshImpulse(class UPrimitiveComponent* Target, const struct FVector& Origin, float ImpulseStrength);
	void UserConstructionScript();
	void F_Interact(class AActor* Owner_0, int32 Wildcard);
	void F_HoverInteract();
	void F_Activate(int32 Wildcard, double Delay, class AActor* Owner_0);
	void F_ReceiveBuff(class AActor* Owner_0, const struct FVector& ReceivedLoc, class UClass* BuffObject);
	void F_KillCombo();
	void F_Channel(class AActor* ChannelingOwner, int32 Wildcard);
	void F_StopChannel(class AActor* ChannelingActor);
	void F_AddImpulseServer(const struct FVector& HitNormal, const struct FVector& Location);
	void F_Bounce(const struct FVector& DirectionAxis, const struct FVector& BounceLoc);
	void F_SetAttachedActor(class AActor* AttachedActor);
	void F_StopInteract(class AActor* Owner_0);
	void F_Activate_Location(const struct FVector& Location, class AActor* Owner_0, int32 Wildcard, class UPrimitiveComponent* Component);
	void F_SendUnlockables(const TArray<class UClass*>& Unlockables);
	void F_TriggerTalisman(class ABP_Item_C* Item, class AActor* WildClassActor);
	void F_StartInteract(class AActor* Owner_0);
	void F_SetCustomMaterialParameter(class FName Param, double Value);
	void F_QuestProgress(class FName Tag);
	void F_EventAlert();
	void F_RemoveBuff(class UClass* BuffObject);
	void F_SetCanBeDestroyedIfNoPlayerAround();
	void F_ServerDamages(double Damages, class UClass* DamageType, class AActor* Causer, E_DamageCategory Element, class FName ItemName);
	void F_PassWildcard(int32 Wildcard);
	void F_ServerExplosion(class FName ExplosionName, double Damages, class AActor* Causer);
	void F_SpawnNiagaraSystemOnEnemy(class UNiagaraSystem* System);
	void F_RemoveNiagaraSystemOnEnemy(class UNiagaraSystem* System);
	void F_BuffManagerClearBuffFromActor(class UClass* Buff);
	void F_StartPhysic(class UPrimitiveComponent* Component, const struct FVector& HitLoc, const struct FVector& Normal, double Strenght, class AActor* hitOwner, E_DamageCategory DamageCategory);
	void ReceiveBeginPlay();
	void F_AutoPhysic();
	void F_Child_PhysicStart(class AActor* Owner_0);
	void F_DamageFeedback(const struct FHitResult& Hit, class AActor* Owner_0, double Damages, class UClass* DamageType, bool Critical, E_DamageCategory Element, class FName ItemName);
	void ExecuteUbergraph_BP_PhysicObject(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_PhysicObject_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_PhysicObject_C")
	}
	static class ABP_PhysicObject_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_PhysicObject_C>();
	}
};
DUMPER7_ASSERTS_ABP_PhysicObject_C;

}

