#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Reward_Skin_Blink

#include "Basic.hpp"

#include "BP_Reward_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Reward_Skin_Blink.BP_Reward_Skin_Blink_C
// 0x0000 (0x0348 - 0x0348)
class ABP_Reward_Skin_Blink_C final : public ABP_Reward_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Reward_Skin_Blink_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Reward_Skin_Blink_C")
	}
	static class ABP_Reward_Skin_Blink_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Reward_Skin_Blink_C>();
	}
};
DUMPER7_ASSERTS_ABP_Reward_Skin_Blink_C;

}

