#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SearchableEngine

#include "Basic.hpp"

#include "E_DamageCategory_structs.hpp"
#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_SearchableEngine.BP_SearchableEngine_C
// 0x0078 (0x0328 - 0x02B0)
class ABP_SearchableEngine_C final : public AActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02B0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBoxComponent*                          Box1;                                              // 0x02B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          Box;                                               // 0x02C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   PreviewMesh;                                       // 0x02C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Mesh;                                              // 0x02D0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        Socket_Mesh;                                       // 0x02D8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        Socket_PreviewScene;                               // 0x02E0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_SmallRockStackB;                                // 0x02E8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_SandMound;                                      // 0x02F0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x02F8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	int32                                         Level;                                             // 0x0300(0x0004)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash)
	bool                                          Finished;                                          // 0x0304(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_305[0x3];                                      // 0x0305(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        levelHeight;                                       // 0x0308(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          isPickedUp;                                        // 0x0310(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_311[0x7];                                      // 0x0311(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void()>              disp_PickUp;                                       // 0x0318(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)

public:
	void ExecuteUbergraph_BP_SearchableEngine(int32 EntryPoint);
	void F_Activate(int32 Wildcard, double Delay, class AActor* Owner_0);
	void F_Activate_Location(const struct FVector& Location, class AActor* Owner_0, int32 Wildcard, class UPrimitiveComponent* Component);
	void F_AddImpulseServer(const struct FVector& HitNormal, const struct FVector& Location);
	void F_Bounce(const struct FVector& DirectionAxis, const struct FVector& BounceLoc);
	void F_BuffManagerClearBuffFromActor(class UClass* Buff);
	void F_CanBeAutoAimed(bool* CanBeAutoAimed, struct FVector* autoAimedLocation);
	void F_Channel(class AActor* ChannelingOwner, int32 Wildcard);
	void F_DamageFeedback(const struct FHitResult& Hit, class AActor* Owner_0, double Damages, class UClass* DamageType, bool Critical, E_DamageCategory Element, class FName ItemName);
	void F_EventAlert();
	void F_GetBuffs(bool* Found, TArray<class UClass*>* BuffObjects);
	void F_GetInteractableDatas(struct FS_InteractableDatas* InteractableDatas);
	void F_GetShootAtLoc(bool* Found, struct FVector* Loc, class USceneComponent** SceneComponent);
	void F_HitMarkerRequest(bool Critical, bool* Receive);
	void F_HoverInteract();
	void F_Interact(class AActor* Owner_0, int32 Wildcard);
	void F_KillCombo();
	void F_PassWildcard(int32 Wildcard);
	void F_PingObject(bool* canBePinged, class UClass** pingActor, class FText* ChatLine, class USceneComponent** AttachedComponent);
	void F_QuestProgress(class FName Tag);
	void F_ReceiveBuff(class AActor* Owner_0, const struct FVector& ReceivedLoc, class UClass* BuffObject);
	void F_RemoveBuff(class UClass* BuffObject);
	void F_RemoveNiagaraSystemOnEnemy(class UNiagaraSystem* System);
	void F_SendUnlockables(const TArray<class UClass*>& Unlockables);
	void F_ServerDamages(double Damages, class UClass* DamageType, class AActor* Causer, E_DamageCategory Element, class FName ItemName);
	void F_ServerExplosion(class FName ExplosionName, double Damages, class AActor* Causer);
	void F_SetAttachedActor(class AActor* AttachedActor);
	void F_SetCanBeDestroyedIfNoPlayerAround();
	void F_SetCustomMaterialParameter(class FName Param, double Value);
	void F_SpawnNiagaraSystemOnEnemy(class UNiagaraSystem* System);
	void F_StartInteract(class AActor* Owner_0);
	void F_StartPhysic(class UPrimitiveComponent* Component, const struct FVector& HitLoc, const struct FVector& Normal, double Strenght, class AActor* hitOwner, E_DamageCategory DamageCategory);
	void F_StopChannel(class AActor* ChannelingActor);
	void F_StopInteract(class AActor* Owner_0);
	void F_TemporaryTick();
	void F_TriggerTalisman(class ABP_Item_C* Item, class AActor* WildClassActor);
	void OnRep_finished();
	void OnRep_isPickedUp();
	void OnRep_Level();
	void ReceiveTick(float DeltaSeconds);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_SearchableEngine_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SearchableEngine_C")
	}
	static class ABP_SearchableEngine_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_SearchableEngine_C>();
	}
};
DUMPER7_ASSERTS_ABP_SearchableEngine_C;

}

