#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Slot_Objective

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Slot_Objective.BP_Slot_Objective_C
// 0x0020 (0x02D0 - 0x02B0)
class ABP_Slot_Objective_C final : public AActor
{
public:
	class USplineComponent*                       Spline;                                            // 0x02B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMesh;                                        // 0x02B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x02C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	int32                                         groupOnMapID;                                      // 0x02C8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          used;                                              // 0x02CC(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void F_AdjustLandscape();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Slot_Objective_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Slot_Objective_C")
	}
	static class ABP_Slot_Objective_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Slot_Objective_C>();
	}
};
DUMPER7_ASSERTS_ABP_Slot_Objective_C;

}

