#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Structure_Cryptic_House_A

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "BP_Structure_classes.hpp"
#include "E_DamageCategory_structs.hpp"
#include "E_Rarity_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Structure_Cryptic_House_A.BP_Structure_Cryptic_House_A_C
// 0x00E0 (0x0398 - 0x02B8)
class ABP_Structure_Cryptic_House_A_C : public ABP_Structure_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02B8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UChildActorComponent*                   BP_CrypticSphere9;                                 // 0x02C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   BP_CrypticSphere8;                                 // 0x02C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   BP_CrypticSphere7;                                 // 0x02D0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   BP_CrypticSphere6;                                 // 0x02D8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   BP_CrypticSphere5;                                 // 0x02E0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   BP_CrypticSphere4;                                 // 0x02E8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   BP_CrypticSphere3;                                 // 0x02F0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   BP_CrypticSphere2;                                 // 0x02F8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   BP_CrypticSphere1;                                 // 0x0300(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   BP_CrypticSphere;                                  // 0x0308(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        Socket_Explosion;                                  // 0x0310(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USpotLightComponent*                    SpotLight;                                         // 0x0318(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UNiagaraComponent*                      NS_Cryptic_FloatingWood_B;                         // 0x0320(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Toilet_Base;                                    // 0x0328(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	double                                        heal;                                              // 0x0330(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         spawnedEnemies;                                    // 0x0338(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         destroyedSpheres;                                  // 0x033C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         amountOfSpheres;                                   // 0x0340(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_344[0x4];                                      // 0x0344(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UClass*                                 spawnedEnemy;                                      // 0x0348(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	int32                                         maxEnemies;                                        // 0x0350(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_354[0x4];                                      // 0x0354(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                estimatedSpawnLoc;                                 // 0x0358(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class UChildActorComponent*>           allSpheres;                                        // 0x0370(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	TArray<class AActor*>                         spawnedActors;                                     // 0x0380(0x0010)(Edit, BlueprintVisible, DisableEditOnTemplate, DisableEditOnInstance)
	bool                                          isOnAlert;                                         // 0x0390(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void F_GetShootAtLoc(bool* Found, struct FVector* Loc, class USceneComponent** SceneComponent);
	void F_CanBeAutoAimed(bool* CanBeAutoAimed, struct FVector* autoAimedLocation);
	void F_PingObject(bool* canBePinged, class UClass** pingActor, class FText* ChatLine, class USceneComponent** AttachedComponent);
	void F_GetInteractableDatas(struct FS_InteractableDatas* InteractableDatas);
	void F_GetBuffs(bool* Found, TArray<class UClass*>* BuffObjects);
	void F_HitMarkerRequest(bool Critical, bool* Receive);
	void F_DestroySpheres();
	void F_DamageFeedback(const struct FHitResult& Hit, class AActor* Owner_0, double Damages, class UClass* DamageType, bool Critical, E_DamageCategory Element, class FName ItemName);
	void F_Interact(class AActor* Owner_0, int32 Wildcard);
	void F_HoverInteract();
	void F_Activate(int32 Wildcard, double Delay, class AActor* Owner_0);
	void F_ReceiveBuff(class AActor* Owner_0, const struct FVector& ReceivedLoc, class UClass* BuffObject);
	void F_KillCombo();
	void F_Channel(class AActor* ChannelingOwner, int32 Wildcard);
	void F_StopChannel(class AActor* ChannelingActor);
	void F_AddImpulseServer(const struct FVector& HitNormal, const struct FVector& Location);
	void F_StartPhysic(class UPrimitiveComponent* Component, const struct FVector& HitLoc, const struct FVector& Normal, double Strenght, class AActor* hitOwner, E_DamageCategory DamageCategory);
	void F_Bounce(const struct FVector& DirectionAxis, const struct FVector& BounceLoc);
	void F_SetAttachedActor(class AActor* AttachedActor);
	void F_StopInteract(class AActor* Owner_0);
	void F_Activate_Location(const struct FVector& Location, class AActor* Owner_0, int32 Wildcard, class UPrimitiveComponent* Component);
	void F_SendUnlockables(const TArray<class UClass*>& Unlockables);
	void F_TriggerTalisman(class ABP_Item_C* Item, class AActor* WildClassActor);
	void F_StartInteract(class AActor* Owner_0);
	void F_SetCustomMaterialParameter(class FName Param, double Value);
	void F_QuestProgress(class FName Tag);
	void F_EventAlert();
	void F_RemoveBuff(class UClass* BuffObject);
	void F_SetCanBeDestroyedIfNoPlayerAround();
	void F_ServerDamages(double Damages, class UClass* DamageType, class AActor* Causer, E_DamageCategory Element, class FName ItemName);
	void F_PassWildcard(int32 Wildcard);
	void F_ServerExplosion(class FName ExplosionName, double Damages, class AActor* Causer);
	void F_SpawnNiagaraSystemOnEnemy(class UNiagaraSystem* System);
	void F_RemoveNiagaraSystemOnEnemy(class UNiagaraSystem* System);
	void F_BuffManagerClearBuffFromActor(class UClass* Buff);
	void ReceiveBeginPlay();
	void F_SpawnCryptic();
	void F_KilLEnemy(class AActor* DestroyedActor);
	void F_DestroySphere(class AActor* DestroyedActor);
	void ReceiveDestroyed();
	void ExecuteUbergraph_BP_Structure_Cryptic_House_A(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Structure_Cryptic_House_A_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Structure_Cryptic_House_A_C")
	}
	static class ABP_Structure_Cryptic_House_A_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Structure_Cryptic_House_A_C>();
	}
};
DUMPER7_ASSERTS_ABP_Structure_Cryptic_House_A_C;

}

