#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Structure_Cryptic_House_E

#include "Basic.hpp"

#include "BP_Structure_Cryptic_House_A_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Structure_Cryptic_House_E.BP_Structure_Cryptic_House_E_C
// 0x0000 (0x0398 - 0x0398)
class ABP_Structure_Cryptic_House_E_C final : public ABP_Structure_Cryptic_House_A_C
{
public:
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Structure_Cryptic_House_E_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Structure_Cryptic_House_E_C")
	}
	static class ABP_Structure_Cryptic_House_E_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Structure_Cryptic_House_E_C>();
	}
};
DUMPER7_ASSERTS_ABP_Structure_Cryptic_House_E_C;

}

