#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: S_PlayerItemJokers

#include "Basic.hpp"


namespace SDK
{

// UserDefinedStruct S_PlayerItemJokers.S_PlayerItemJokers
// 0x0030 (0x0030 - 0x0000)
struct FS_PlayerItemJokers final
{
public:
	class FName                                   jokerA_3_23C049D0462EEF85DCEED5A552CB20C6;         // 0x0000(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   jokerB_5_6F57743649A6BCBB31FA92AB586E5927;         // 0x0008(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   jokerC_7_CAA1435144DD919464E77BBC212050C1;         // 0x0010(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   jokerD_9_FBF331A148DB2793079596AA71EF8375;         // 0x0018(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class FName>                           jokers_13_7822C195413EA2810E969F8C260AA8B6;        // 0x0020(0x0010)(Edit, BlueprintVisible)
};
DUMPER7_ASSERTS_FS_PlayerItemJokers;

}

