#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: S_PlayerRuntimeLeaderboard

#include "Basic.hpp"


namespace SDK
{

// UserDefinedStruct S_PlayerRuntimeLeaderboard.S_PlayerRuntimeLeaderboard
// 0x0110 (0x0110 - 0x0000)
struct FS_PlayerRuntimeLeaderboard final
{
public:
	int32                                         enemies_2_9973937A40A8847C477EFABB3A8ED2FB;        // 0x0000(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         deaths_6_E827D02A4AC7FB19897FA9ADB3064FDC;         // 0x0004(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         spells_8_C39DCED7499CDBCE346B7087F1CB363E;         // 0x0008(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         shots_10_C6AE8BC44D8C7912EAC7E699B1AF3667;         // 0x000C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         revives_13_9BCA79464C7F7ABF257AF885998B9569;       // 0x0010(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         xpWepA_19_D8723478447C97368BB9D0B2FAB77D93;        // 0x0014(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         xpWepB_21_D62183594C63FD8064B58C8427E41CC0;        // 0x0018(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TMap<class FName, int32>                      xp_30_BE3C424C4531CC92B29C218A50B39BFE;            // 0x0020(0x0050)(Edit, BlueprintVisible)
	TMap<class FName, double>                     itemDamages_37_459AA0EF4C7AEA0A0B4EEA816F22EDCB;   // 0x0070(0x0050)(Edit, BlueprintVisible)
	TMap<class FName, int32>                      itemKills_43_CBE876614A89C77F9C985AB017057128;     // 0x00C0(0x0050)(Edit, BlueprintVisible)
};
DUMPER7_ASSERTS_FS_PlayerRuntimeLeaderboard;

}

