#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: STT_Attack_Gunner

#include "Basic.hpp"

#include "StateTreeModule_structs.hpp"


namespace SDK::Params
{

// Function STT_Attack_Gunner.STT_Attack_Gunner_C.ExecuteUbergraph_STT_Attack_Gunner
// 0x0050 (0x0050 - 0x0000)
struct STT_Attack_Gunner_C_ExecuteUbergraph_STT_Attack_Gunner final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_6[0x2];                                        // 0x0006(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FStateTreeTransitionResult             K2Node_Event_Transition;                           // 0x0008(0x0040)(ConstParm)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_STT_Attack_Gunner_C_ExecuteUbergraph_STT_Attack_Gunner;

// Function STT_Attack_Gunner.STT_Attack_Gunner_C.ReceiveLatentEnterState
// 0x0040 (0x0040 - 0x0000)
struct STT_Attack_Gunner_C_ReceiveLatentEnterState final
{
public:
	struct FStateTreeTransitionResult             Transition;                                        // 0x0000(0x0040)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
DUMPER7_ASSERTS_STT_Attack_Gunner_C_ReceiveLatentEnterState;

}

