#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: STT_ChaseTargetFlying

#include "Basic.hpp"

#include "STT_ChaseTargetFlying_classes.hpp"
#include "STT_ChaseTargetFlying_parameters.hpp"


namespace SDK
{

// Function STT_ChaseTargetFlying.STT_ChaseTargetFlying_C.ExecuteUbergraph_STT_ChaseTargetFlying
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USTT_ChaseTargetFlying_C::ExecuteUbergraph_STT_ChaseTargetFlying(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("STT_ChaseTargetFlying_C", "ExecuteUbergraph_STT_ChaseTargetFlying");

	Params::STT_ChaseTargetFlying_C_ExecuteUbergraph_STT_ChaseTargetFlying Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function STT_ChaseTargetFlying.STT_ChaseTargetFlying_C.F_GetLocationInPlayerView
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FVector&                   startLoc                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   targetLoc                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool*                                   foundLoc                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FVector*                         Loc                                                    (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USTT_ChaseTargetFlying_C::F_GetLocationInPlayerView(const struct FVector& startLoc, const struct FVector& targetLoc, bool* foundLoc, struct FVector* Loc)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("STT_ChaseTargetFlying_C", "F_GetLocationInPlayerView");

	Params::STT_ChaseTargetFlying_C_F_GetLocationInPlayerView Parms{};

	Parms.startLoc = std::move(startLoc);
	Parms.targetLoc = std::move(targetLoc);

	UObject::ProcessEvent(Func, &Parms);

	if (foundLoc != nullptr)
		*foundLoc = Parms.foundLoc;

	if (Loc != nullptr)
		*Loc = std::move(Parms.Loc);
}


// Function STT_ChaseTargetFlying.STT_ChaseTargetFlying_C.F_IsTargetInView
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FVector&                   startLoc                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   targetLoc                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool*                                   InView                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USTT_ChaseTargetFlying_C::F_IsTargetInView(const struct FVector& startLoc, const struct FVector& targetLoc, bool* InView)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("STT_ChaseTargetFlying_C", "F_IsTargetInView");

	Params::STT_ChaseTargetFlying_C_F_IsTargetInView Parms{};

	Parms.startLoc = std::move(startLoc);
	Parms.targetLoc = std::move(targetLoc);

	UObject::ProcessEvent(Func, &Parms);

	if (InView != nullptr)
		*InView = Parms.InView;
}


// Function STT_ChaseTargetFlying.STT_ChaseTargetFlying_C.F_StartMovement
// (Public, BlueprintCallable, BlueprintEvent)

void USTT_ChaseTargetFlying_C::F_StartMovement()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("STT_ChaseTargetFlying_C", "F_StartMovement");

	UObject::ProcessEvent(Func, nullptr);
}


// Function STT_ChaseTargetFlying.STT_ChaseTargetFlying_C.OnMoveFinished_12B4EA6F4865E4FE6D0DE490CF838A74
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EPathFollowingResult                    Result                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AAIController*                    AIController                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void USTT_ChaseTargetFlying_C::OnMoveFinished_12B4EA6F4865E4FE6D0DE490CF838A74(EPathFollowingResult Result, class AAIController* AIController)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("STT_ChaseTargetFlying_C", "OnMoveFinished_12B4EA6F4865E4FE6D0DE490CF838A74");

	Params::STT_ChaseTargetFlying_C_OnMoveFinished_12B4EA6F4865E4FE6D0DE490CF838A74 Parms{};

	Parms.Result = Result;
	Parms.AIController = AIController;

	UObject::ProcessEvent(Func, &Parms);
}


// Function STT_ChaseTargetFlying.STT_ChaseTargetFlying_C.OnRequestFailed_12B4EA6F4865E4FE6D0DE490CF838A74
// (BlueprintCallable, BlueprintEvent)

void USTT_ChaseTargetFlying_C::OnRequestFailed_12B4EA6F4865E4FE6D0DE490CF838A74()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("STT_ChaseTargetFlying_C", "OnRequestFailed_12B4EA6F4865E4FE6D0DE490CF838A74");

	UObject::ProcessEvent(Func, nullptr);
}


// Function STT_ChaseTargetFlying.STT_ChaseTargetFlying_C.ReceiveLatentEnterState
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FStateTreeTransitionResult&Transition                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void USTT_ChaseTargetFlying_C::ReceiveLatentEnterState(const struct FStateTreeTransitionResult& Transition)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("STT_ChaseTargetFlying_C", "ReceiveLatentEnterState");

	Params::STT_ChaseTargetFlying_C_ReceiveLatentEnterState Parms{};

	Parms.Transition = std::move(Transition);

	UObject::ProcessEvent(Func, &Parms);
}

}

