#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Contract_Modifier_Tooltip

#include "Basic.hpp"

#include "UI_Contract_Modifier_Tooltip_classes.hpp"
#include "UI_Contract_Modifier_Tooltip_parameters.hpp"


namespace SDK
{

// Function UI_Contract_Modifier_Tooltip.UI_Contract_Modifier_Tooltip_C.ExecuteUbergraph_UI_Contract_Modifier_Tooltip
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Contract_Modifier_Tooltip_C::ExecuteUbergraph_UI_Contract_Modifier_Tooltip(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Contract_Modifier_Tooltip_C", "ExecuteUbergraph_UI_Contract_Modifier_Tooltip");

	Params::UI_Contract_Modifier_Tooltip_C_ExecuteUbergraph_UI_Contract_Modifier_Tooltip Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Contract_Modifier_Tooltip.UI_Contract_Modifier_Tooltip_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Contract_Modifier_Tooltip_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Contract_Modifier_Tooltip_C", "PreConstruct");

	Params::UI_Contract_Modifier_Tooltip_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

