#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Equipment_ItemSelection_WeaponA

#include "Basic.hpp"

#include "UI_Equipment_ItemSelection_WeaponA_classes.hpp"
#include "UI_Equipment_ItemSelection_WeaponA_parameters.hpp"


namespace SDK
{

// Function UI_Equipment_ItemSelection_WeaponA.UI_Equipment_ItemSelection_WeaponA_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUI_Equipment_ItemSelection_WeaponA_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Equipment_ItemSelection_WeaponA_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Equipment_ItemSelection_WeaponA.UI_Equipment_ItemSelection_WeaponA_C.ExecuteUbergraph_UI_Equipment_ItemSelection_WeaponA
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Equipment_ItemSelection_WeaponA_C::ExecuteUbergraph_UI_Equipment_ItemSelection_WeaponA(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Equipment_ItemSelection_WeaponA_C", "ExecuteUbergraph_UI_Equipment_ItemSelection_WeaponA");

	Params::UI_Equipment_ItemSelection_WeaponA_C_ExecuteUbergraph_UI_Equipment_ItemSelection_WeaponA Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

