#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Joker_Slot

#include "Basic.hpp"

#include "UI_Joker_Slot_classes.hpp"
#include "UI_Joker_Slot_parameters.hpp"


namespace SDK
{

// Function UI_Joker_Slot.UI_Joker_Slot_C.BndEvt__UI_EpicTweak_Slot_Button_Tweak_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UUI_Joker_Slot_C::BndEvt__UI_EpicTweak_Slot_Button_Tweak_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Joker_Slot_C", "BndEvt__UI_EpicTweak_Slot_Button_Tweak_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Joker_Slot.UI_Joker_Slot_C.BndEvt__UI_EpicTweak_Slot_Button_Tweak_K2Node_ComponentBoundEvent_2_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UUI_Joker_Slot_C::BndEvt__UI_EpicTweak_Slot_Button_Tweak_K2Node_ComponentBoundEvent_2_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Joker_Slot_C", "BndEvt__UI_EpicTweak_Slot_Button_Tweak_K2Node_ComponentBoundEvent_2_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Joker_Slot.UI_Joker_Slot_C.BndEvt__UI_Joker_Slot_Button_Tweak_K2Node_ComponentBoundEvent_3_OnButtonPressedEvent__DelegateSignature
// (BlueprintEvent)

void UUI_Joker_Slot_C::BndEvt__UI_Joker_Slot_Button_Tweak_K2Node_ComponentBoundEvent_3_OnButtonPressedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Joker_Slot_C", "BndEvt__UI_Joker_Slot_Button_Tweak_K2Node_ComponentBoundEvent_3_OnButtonPressedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Joker_Slot.UI_Joker_Slot_C.ExecuteUbergraph_UI_Joker_Slot
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Joker_Slot_C::ExecuteUbergraph_UI_Joker_Slot(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Joker_Slot_C", "ExecuteUbergraph_UI_Joker_Slot");

	Params::UI_Joker_Slot_C_ExecuteUbergraph_UI_Joker_Slot Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Joker_Slot.UI_Joker_Slot_C.F_CheckIfJokerIsStillAvailable
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   StillAvailable                                         (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Joker_Slot_C::F_CheckIfJokerIsStillAvailable(bool* StillAvailable)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Joker_Slot_C", "F_CheckIfJokerIsStillAvailable");

	Params::UI_Joker_Slot_C_F_CheckIfJokerIsStillAvailable Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (StillAvailable != nullptr)
		*StillAvailable = Parms.StillAvailable;
}


// Function UI_Joker_Slot.UI_Joker_Slot_C.F_ClickButton
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UButton*                          ClickedButton                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UUI_Joker_Slot_C::F_ClickButton(class UButton* ClickedButton)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Joker_Slot_C", "F_ClickButton");

	Params::UI_Joker_Slot_C_F_ClickButton Parms{};

	Parms.ClickedButton = ClickedButton;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Joker_Slot.UI_Joker_Slot_C.F_Refresh
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             jokerName_0                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Joker_Slot_C::F_Refresh(class FName jokerName_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Joker_Slot_C", "F_Refresh");

	Params::UI_Joker_Slot_C_F_Refresh Parms{};

	Parms.jokerName_0 = jokerName_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Joker_Slot.UI_Joker_Slot_C.F_ReleaseButton
// (Public, BlueprintCallable, BlueprintEvent)

void UUI_Joker_Slot_C::F_ReleaseButton()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Joker_Slot_C", "F_ReleaseButton");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Joker_Slot.UI_Joker_Slot_C.F_RemoveJokerFromArray
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<class FName>&                    TargetArray                                            (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// const class FName&                      JokerToRemove                                          (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Joker_Slot_C::F_RemoveJokerFromArray(TArray<class FName>& TargetArray, const class FName& JokerToRemove)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Joker_Slot_C", "F_RemoveJokerFromArray");

	Params::UI_Joker_Slot_C_F_RemoveJokerFromArray Parms{};

	Parms.TargetArray = std::move(TargetArray);
	Parms.JokerToRemove = JokerToRemove;

	UObject::ProcessEvent(Func, &Parms);

	TargetArray = std::move(Parms.TargetArray);
}


// Function UI_Joker_Slot.UI_Joker_Slot_C.F_RemoveJokerFromItem
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UUI_Joker_Slot_C::F_RemoveJokerFromItem()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Joker_Slot_C", "F_RemoveJokerFromItem");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Joker_Slot.UI_Joker_Slot_C.F_SelectItem
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UClass*                           Item                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// E_ItemCategory                          Category                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   SpellSlot                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Joker_Slot_C::F_SelectItem(class UClass* Item, E_ItemCategory Category, int32 SpellSlot)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Joker_Slot_C", "F_SelectItem");

	Params::UI_Joker_Slot_C_F_SelectItem Parms{};

	Parms.Item = Item;
	Parms.Category = Category;
	Parms.SpellSlot = SpellSlot;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Joker_Slot.UI_Joker_Slot_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Joker_Slot_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Joker_Slot_C", "PreConstruct");

	Params::UI_Joker_Slot_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

