#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Lifebar

#include "Basic.hpp"

#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_Lifebar.UI_Lifebar_C
// 0x0008 (0x0330 - 0x0328)
class UUI_Lifebar_C final : public UUserWidget
{
public:
	class UProgressBar*                           ProgressBar_Boss;                                  // 0x0328(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("UI_Lifebar_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UI_Lifebar_C")
	}
	static class UUI_Lifebar_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_Lifebar_C>();
	}
};
DUMPER7_ASSERTS_UUI_Lifebar_C;

}

