#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Menu_Container_OptionsHolder

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UI_Menu_Container_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_Menu_Container_OptionsHolder.UI_Menu_Container_OptionsHolder_C
// 0x0048 (0x0380 - 0x0338)
class UUI_Menu_Container_OptionsHolder_C final : public UUI_Menu_Container_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_UI_Menu_Container_OptionsHolder_C;  // 0x0338(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UUI_Template_LargeButton_C*             UI_Template_Video;                                 // 0x0340(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_Template_LargeButton_C*             UI_Template_Controls_Backups;                      // 0x0348(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_Template_LargeButton_C*             UI_Template_Controls_Accessibility;                // 0x0350(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_Template_LargeButton_C*             UI_Template_Controls;                              // 0x0358(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_Template_LargeButton_C*             UI_Template_Audio;                                 // 0x0360(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               Overlay_Holder;                                    // 0x0368(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetAnimation*                       Appear;                                            // 0x0370(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UUserWidget*                            childWidget;                                       // 0x0378(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)

public:
	void F_Blackscreen();
	void BndEvt__UI_Menu_Container_Options_UI_Template_Video_K2Node_ComponentBoundEvent_6_disp_Click__DelegateSignature(int32 ID, class FName Wildcard);
	void BndEvt__UI_Menu_Container_Options_UI_Template_Audio_K2Node_ComponentBoundEvent_7_disp_Click__DelegateSignature(int32 ID, class FName Wildcard);
	void BndEvt__UI_Menu_Container_Options_UI_Template_Controls_K2Node_ComponentBoundEvent_8_disp_Click__DelegateSignature(int32 ID, class FName Wildcard);
	void BndEvt__UI_Menu_Container_Options_UI_Template_Controls_Accessibility_K2Node_ComponentBoundEvent_0_disp_Click__DelegateSignature(int32 ID, class FName Wildcard);
	void F_OpenWidget(class UClass* Class_0);
	void Construct();
	void BndEvt__UI_Menu_Container_OptionsHolder_UI_Template_Controls_Backups_K2Node_ComponentBoundEvent_1_disp_Click__DelegateSignature(int32 ID, class FName Wildcard);
	void ExecuteUbergraph_UI_Menu_Container_OptionsHolder(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("UI_Menu_Container_OptionsHolder_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UI_Menu_Container_OptionsHolder_C")
	}
	static class UUI_Menu_Container_OptionsHolder_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_Menu_Container_OptionsHolder_C>();
	}
};
DUMPER7_ASSERTS_UUI_Menu_Container_OptionsHolder_C;

}

