#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_NpcTalk_Key

#include "Basic.hpp"

#include "UI_NpcTalk_Key_classes.hpp"
#include "UI_NpcTalk_Key_parameters.hpp"


namespace SDK
{

// Function UI_NpcTalk_Key.UI_NpcTalk_Key_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUI_NpcTalk_Key_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_NpcTalk_Key_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_NpcTalk_Key.UI_NpcTalk_Key_C.ExecuteUbergraph_UI_NpcTalk_Key
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_NpcTalk_Key_C::ExecuteUbergraph_UI_NpcTalk_Key(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_NpcTalk_Key_C", "ExecuteUbergraph_UI_NpcTalk_Key");

	Params::UI_NpcTalk_Key_C_ExecuteUbergraph_UI_NpcTalk_Key Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

