#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_ObtainedJoker

#include "Basic.hpp"

#include "UI_ObtainedJoker_classes.hpp"
#include "UI_ObtainedJoker_parameters.hpp"


namespace SDK
{

// Function UI_ObtainedJoker.UI_ObtainedJoker_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUI_ObtainedJoker_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ObtainedJoker_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_ObtainedJoker.UI_ObtainedJoker_C.ExecuteUbergraph_UI_ObtainedJoker
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_ObtainedJoker_C::ExecuteUbergraph_UI_ObtainedJoker(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ObtainedJoker_C", "ExecuteUbergraph_UI_ObtainedJoker");

	Params::UI_ObtainedJoker_C_ExecuteUbergraph_UI_ObtainedJoker Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_ObtainedJoker.UI_ObtainedJoker_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_ObtainedJoker_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_ObtainedJoker_C", "PreConstruct");

	Params::UI_ObtainedJoker_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

